// disable typescript in this file
// @ts-nocheck

import { uuid } from "@/lib/utils";
import { useState } from "react";
import { useForm } from "react-hook-form";

export default function Form({
  defaultValues = {},
  onSubmit = (_value) => {},
}) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    defaultValues,
  });

  // console.log(errors);
  /* 
    fullname       
    gender         
    age            
    religion       
    course         
    year           
    specialization 
    section        
    municipality   
    province       
    familyType     
  */

  // generate letters from A to Z
  const letters = Array.from(Array(26), (_, i) => String.fromCharCode(65 + i));

  // province and municipalities
  const provinceList = {
    AURORA: {
      municipality_list: {
        BALER: {
          barangay_list: [
            "BARANGAY I (POB.)",
            "BARANGAY II (POB.)",
            "BARANGAY III (POB.)",
            "BARANGAY IV (POB.)",
            "BARANGAY V (POB.)",
            "BUHANGIN",
            "CALABUANAN",
            "OBLIGACION",
            "PINGIT",
            "RESERVA",
            "SABANG",
            "SUCLAYIN",
            "ZABALI",
          ],
        },
        CASIGURAN: {
          barangay_list: [
            "BARANGAY 1 (POB.)",
            "BARANGAY 2 (POB.)",
            "BARANGAY 3 (POB.)",
            "BARANGAY 4 (POB.)",
            "BARANGAY 5 (POB.)",
            "BARANGAY 6 (POB.)",
            "BARANGAY 7 (POB.)",
            "BARANGAY 8 (POB.)",
            "BIANUAN",
            "CALABGAN",
            "CALANGCUASAN",
            "CALANTAS",
            "COZO",
            "CULAT",
            "DIBACONG",
            "DIBET",
            "DITINAGYAN",
            "ESPERANZA",
            "ESTEVES",
            "LUAL",
            "MARIKIT",
            "SAN ILDEFONSO",
            "TABAS",
            "TINIB",
          ],
        },
        DILASAG: {
          barangay_list: [
            "DIAGYAN",
            "DICABASAN",
            "DILAGUIDI",
            "DIMASESET",
            "DINIOG",
            "ESPERANZA",
            "LAWANG",
            "MALIGAYA (POB.)",
            "MANGGITAHAN",
            "MASAGANA (POB.)",
            "URA",
          ],
        },
        DINALUNGAN: {
          barangay_list: [
            "ABULEG",
            "DIBARAYBAY",
            "DITAWINI",
            "MAPALAD",
            "NIPOO (BULO)",
            "PALEG",
            "SIMBAHAN",
            "ZONE I (POB.)",
            "ZONE II (POB.)",
          ],
        },
        DINGALAN: {
          barangay_list: [
            "APLAYA",
            "BUTAS NA BATO",
            "CABOG (MATAWE)",
            "CARAGSACAN",
            "DAVILDAVILAN",
            "DIKAPANIKIAN",
            "IBONA",
            "PALTIC",
            "POBLACION",
            "TANAWAN",
            "UMIRAY (MALAMIG)",
          ],
        },
        DIPACULAO: {
          barangay_list: [
            "BAYABAS",
            "BORLONGAN",
            "BUENAVISTA",
            "CALAOCAN",
            "DIAMANEN",
            "DIANED",
            "DIARABASIN",
            "DIBUTUNAN",
            "DIMABUNO",
            "DINADIAWAN",
            "DITALE",
            "GUPA",
            "IPIL",
            "LABOY",
            "LIPIT",
            "LOBBOT",
            "MALIGAYA",
            "MIJARES",
            "MUCDOL",
            "NORTH POBLACION",
            "PUANGI",
            "SALAY",
            "SAPANGKAWAYAN",
            "SOUTH POBLACION",
            "TOYTOYAN",
          ],
        },
        "MARIA AURORA": {
          barangay_list: [
            "ALCALA",
            "BAGTU",
            "BANGCO",
            "BANNAWAG",
            "BARANGAY I (POB.)",
            "BARANGAY II (POB.)",
            "BARANGAY III (POB.)",
            "BARANGAY IV (POB.)",
            "BAUBO",
            "BAYANIHAN",
            "BAZAL",
            "CABITUCULAN EAST",
            "CABITUCULAN WEST",
            "CADAYACAN",
            "DEBUCAO",
            "DECOLIAT",
            "DETAILEN",
            "DIAAT",
            "DIALATMAN",
            "DIAMAN",
            "DIANAWAN",
            "DIKILDIT",
            "DIMANPUDSO",
            "DIOME",
            "ESTONILO",
            "FLORIDA",
            "GALINTUJA",
            "MALASIN",
            "PONGLO",
            "QUIRINO",
            "RAMADA",
            "SAN JOAQUIN",
            "SAN JOSE",
            "SAN JUAN",
            "SAN LEONARDO",
            "SANTA LUCIA",
            "SANTO TOMAS",
            "SUGUIT",
            "VILLA AURORA",
            "WENCESLAO",
          ],
        },
        "SAN LUIS": {
          barangay_list: [
            "BACONG",
            "BARANGAY I (POB.)",
            "BARANGAY II (POB.)",
            "BARANGAY III (POB.)",
            "BARANGAY IV (POB.)",
            "DIBALO",
            "DIBAYABAY",
            "DIBUT",
            "DIKAPINISAN",
            "DIMANAYAT",
            "DITEKI",
            "DITUMABO",
            "L. PIMENTEL",
            "NONONG SENIOR",
            "REAL",
            "SAN ISIDRO",
            "SAN JOSE",
            "ZARAH",
          ],
        },
      },
    },
    BATAAN: {
      municipality_list: {
        ABUCAY: {
          barangay_list: [
            "BANGKAL",
            "CALAYLAYAN (POB.)",
            "CAPITANGAN",
            "GABON",
            "LAON (POB.)",
            "MABATANG",
            "OMBOY",
            "SALIAN",
            "WAWA (POB.)",
          ],
        },
        BAGAC: {
          barangay_list: [
            "ATILANO L. RICARDO",
            "BAGUMBAYAN (POB.)",
            "BANAWANG",
            "BINUANGAN",
            "BINUKAWAN",
            "IBABA",
            "IBIS",
            "PAG-ASA (WAWA-SIBACAN)",
            "PARANG",
            "PAYSAWAN",
            "QUINAWAN",
            "SAN ANTONIO",
            "SAYSAIN",
            "TABING-ILOG (POB.)",
          ],
        },
        "BALANGA CITY": {
          barangay_list: [
            "BAGONG SILANG",
            "BAGUMBAYAN",
            "CABOG-CABOG",
            "CAMACHO",
            "CATANING",
            "CENTRAL",
            "CUPANG NORTH",
            "CUPANG PROPER",
            "CUPANG WEST",
            "DANGCOL (BERNABE)",
            "DOÑA FRANCISCA",
            "IBAYO",
            "LOTE",
            "MALABIA",
            "MUNTING BATANGAS (CADRE)",
            "POBLACION",
            "PTO. RIVAS IBABA",
            "PTO. RIVAS ITAAS",
            "SAN JOSE",
            "SIBACAN",
            "TALISAY",
            "TANATO",
            "TENEJERO",
            "TORTUGAS",
            "TUYO",
          ],
        },
        DINALUPIHAN: {
          barangay_list: [
            "AQUINO",
            "BANGAL",
            "BAYAN-BAYANAN",
            "BONIFACIO (POB.)",
            "BURGOS (POB.)",
            "COLO",
            "DAANG BAGO",
            "DALAO",
            "DEL PILAR (POB.)",
            "GEN. LUNA (POB.)",
            "GOMEZ (POB.)",
            "HAPPY VALLEY",
            "JOSE C. PAYUMO, JR.",
            "KATAASAN",
            "LAYAC",
            "LUACAN",
            "MABINI EXT. (POB.)",
            "MABINI PROPER (POB.)",
            "MAGSAYSAY",
            "MALIGAYA",
            "NAPARING",
            "NEW SAN JOSE",
            "OLD SAN JOSE",
            "PADRE DANDAN (POB.)",
            "PAG-ASA",
            "PAGALANGGANG",
            "PAYANGAN",
            "PENTOR",
            "PINULOT",
            "PITA",
            "RIZAL (POB.)",
            "ROOSEVELT",
            "ROXAS (POB.)",
            "SAGUING",
            "SAN BENITO",
            "SAN ISIDRO (POB.)",
            "SAN PABLO (BULATE)",
            "SAN RAMON",
            "SAN SIMON",
            "SANTA ISABEL (TABACAN)",
            "SANTO NIÑO",
            "SAPANG BALAS",
            "TORRES BUGAUEN (POB.)",
            "TUBO-TUBO",
            "TUCOP",
            "ZAMORA (POB.)",
          ],
        },
        HERMOSA: {
          barangay_list: [
            "A. RIVERA (POB.)",
            "ALMACEN",
            "BACONG",
            "BALSIC",
            "BAMBAN",
            "BURGOS-SOLIMAN (POB.)",
            "CATANING (POB.)",
            "CULIS",
            "DAUNGAN (POB.)",
            "JUDGE ROMAN CRUZ SR. (MANDAMA)",
            "MABIGA",
            "MABUCO",
            "MAITE",
            "MAMBOG - MANDAMA",
            "PALIHAN",
            "PANDATUNG",
            "PULO",
            "SABA",
            "SACRIFICE VALLEY",
            "SAN PEDRO (POB.)",
            "SANTO CRISTO (POB.)",
            "SUMALO",
            "TIPO",
          ],
        },
        LIMAY: {
          barangay_list: [
            "ALANGAN",
            "DUALE",
            "KITANG 2 AND LUZ",
            "KITANG I",
            "LAMAO",
            "LANDING",
            "POBLACION",
            "REFORMISTA",
            "SAN FRANCISCO DE ASIS",
            "ST. FRANCIS II",
            "TOWNSITE",
            "WAWA",
          ],
        },
        MARIVELES: {
          barangay_list: [
            "ALAS-ASIN",
            "ALION",
            "BALON-ANITO",
            "BASECO COUNTRY (NASSCO)",
            "BATANGAS II",
            "BIAAN",
            "CABCABEN",
            "CAMAYA",
            "IPAG",
            "LUCANIN",
            "MALAYA",
            "MALIGAYA",
            "MT. VIEW",
            "POBLACION",
            "SAN CARLOS",
            "SAN ISIDRO",
            "SISIMAN",
            "TOWNSITE",
          ],
        },
        MORONG: {
          barangay_list: [
            "BINARITAN",
            "MABAYO",
            "NAGBALAYONG",
            "POBLACION",
            "SABANG",
          ],
        },
        ORANI: {
          barangay_list: [
            "APOLLO",
            "BAGONG PARAISO (POB.)",
            "BALUT (POB.)",
            "BAYAN (POB.)",
            "CALERO (POB.)",
            "CENTRO I (POB.)",
            "CENTRO II (POB.)",
            "DONA",
            "KABALUTAN",
            "KAPARANGAN",
            "MARIA FE",
            "MASANTOL",
            "MULAWIN",
            "PAG-ASA",
            "PAKING-CARBONERO (POB.)",
            "PALIHAN (POB.)",
            "PANTALAN BAGO (POB.)",
            "PANTALAN LUMA (POB.)",
            "PARANG PARANG (POB.)",
            "PUKSUAN",
            "SIBUL",
            "SILAHIS",
            "TAGUMPAY",
            "TALA",
            "TALIMUNDOC",
            "TAPULAO",
            "TENEJERO (POB.)",
            "TUGATOG",
            "WAWA (POB.)",
          ],
        },
        ORION: {
          barangay_list: [
            "ARELLANO (POB.)",
            "BAGUMBAYAN (POB.)",
            "BALAGTAS (POB.)",
            "BALUT (POB.)",
            "BANTAN",
            "BILOLO",
            "CALUNGUSAN",
            "CAMACHILE",
            "DAANG BAGO (POB.)",
            "DAANG BILOLO (POB.)",
            "DAANG PARE",
            "GENERAL LIM (KAPUT)",
            "KAPUNITAN",
            "LATI (POB.)",
            "LUSUNGAN (POB.)",
            "PUTING BUHANGIN",
            "SABATAN",
            "SAN VICENTE (POB.)",
            "SANTA ELENA",
            "SANTO DOMINGO",
            "VILLA ANGELES (POB.)",
            "WAKAS (POB.)",
            "WAWA (POB.)",
          ],
        },
        PILAR: {
          barangay_list: [
            "ALA-ULI",
            "BAGUMBAYAN",
            "BALUT I",
            "BALUT II",
            "BANTAN MUNTI",
            "BURGOS",
            "DEL ROSARIO (POB.)",
            "DIWA",
            "LANDING",
            "LIYANG",
            "NAGWALING",
            "PANILAO",
            "PANTINGAN",
            "POBLACION",
            "RIZAL (POB.)",
            "SANTA ROSA",
            "WAKAS NORTH",
            "WAKAS SOUTH",
            "WAWA",
          ],
        },
        SAMAL: {
          barangay_list: [
            "EAST CALAGUIMAN (POB.)",
            "EAST DAANG BAGO (POB.)",
            "GUGO",
            "IBABA (POB.)",
            "IMELDA",
            "LALAWIGAN",
            "PALILI",
            "SAN JUAN (POB.)",
            "SAN ROQUE (POB.)",
            "SANTA LUCIA",
            "SAPA",
            "TABING ILOG",
            "WEST CALAGUIMAN (POB.)",
            "WEST DAANG BAGO (POB.)",
          ],
        },
      },
    },
    BULACAN: {
      municipality_list: {
        ANGAT: {
          barangay_list: [
            "BANABAN",
            "BAYBAY",
            "BINAGBAG",
            "DONACION",
            "ENCANTO",
            "LAOG",
            "MARUNGKO",
            "NIUGAN",
            "PALTOK",
            "PULONG YANTOK",
            "SAN ROQUE (POB.)",
            "SANTA CRUZ (POB.)",
            "SANTA LUCIA",
            "SANTO CRISTO (POB.)",
            "SULUCAN",
            "TABOC",
          ],
        },
        "BALAGTAS (BIGAA)": {
          barangay_list: [
            "BOROL 1ST",
            "BOROL 2ND",
            "DALIG",
            "LONGOS",
            "PANGINAY",
            "PULONG GUBAT",
            "SAN JUAN",
            "SANTOL",
            "WAWA (POB.)",
          ],
        },
        BALIUAG: {
          barangay_list: [
            "BAGONG NAYON",
            "BARANGCA",
            "CALANTIPAY",
            "CATULINAN",
            "CONCEPCION",
            "HINUKAY",
            "MAKINABANG",
            "MATANGTUBIG",
            "PAGALA",
            "PAITAN",
            "PIEL",
            "PINAGBARILAN",
            "POBLACION",
            "SABANG",
            "SAN JOSE",
            "SAN ROQUE",
            "SANTA BARBARA",
            "SANTO CRISTO",
            "SANTO NIÑO",
            "SUBIC",
            "SULIVAN",
            "TANGOS",
            "TARCAN",
            "TIAONG",
            "TIBAG",
            "TILAPAYONG",
            "VIRGEN DELAS FLORES",
          ],
        },
        BOCAUE: {
          barangay_list: [
            "ANTIPONA",
            "BAGUMBAYAN",
            "BAMBANG",
            "BATIA",
            "BIÑANG 1ST",
            "BIÑANG 2ND",
            "BOLACAN",
            "BUNDUKAN",
            "BUNLO",
            "CAINGIN",
            "DUHAT",
            "IGULOT",
            "LOLOMBOY",
            "POBLACION",
            "SULUCAN",
            "TAAL",
            "TAMBOBONG",
            "TURO",
            "WAKAS",
          ],
        },
        BULACAN: {
          barangay_list: [
            "BAGUMBAYAN",
            "BALUBAD",
            "BAMBANG",
            "MATUNGAO",
            "MAYSANTOL",
            "PEREZ",
            "PITPITAN",
            "SAN FRANCISCO",
            "SAN JOSE (POB.)",
            "SAN NICOLAS",
            "SANTA ANA",
            "SANTA INES",
            "TALIPTIP",
            "TIBIG",
          ],
        },
        BUSTOS: {
          barangay_list: [
            "BONGA MAYOR",
            "BONGA MENOR",
            "BUISAN",
            "CAMACHILIHAN",
            "CAMBAOG",
            "CATACTE",
            "LICIADA",
            "MALAMIG",
            "MALAWAK",
            "POBLACION",
            "SAN PEDRO",
            "TALAMPAS",
            "TANAWAN",
            "TIBAGAN",
          ],
        },
        CALUMPIT: {
          barangay_list: [
            "BALITE",
            "BALUNGAO",
            "BUGUION",
            "BULUSAN",
            "CALIZON",
            "CALUMPANG",
            "CANIOGAN",
            "CORAZON",
            "FRANCES",
            "GATBUCA",
            "GUGO",
            "IBA ESTE",
            "IBA O'ESTE",
            "LONGOS",
            "MEYSULAO",
            "MEYTO",
            "PALIMBANG",
            "PANDUCOT",
            "PIO CRUZCOSA",
            "POBLACION",
            "PUNGO",
            "SAN JOSE",
            "SAN MARCOS",
            "SAN MIGUEL",
            "SANTA LUCIA",
            "SANTO NIÑO",
            "SAPANG BAYAN",
            "SERGIO BAYAN",
            "SUCOL",
          ],
        },
        "DOÑA REMEDIOS TRINIDAD": {
          barangay_list: [
            "BAYABAS",
            "CAMACHILE",
            "CAMACHIN",
            "KABAYUNAN",
            "KALAWAKAN",
            "PULONG SAMPALOK",
            "SAPANG BULAK",
            "TALBAK",
          ],
        },
        GUIGUINTO: {
          barangay_list: [
            "CUTCUT",
            "DAUNGAN",
            "ILANG-ILANG",
            "MALIS",
            "PANGINAY",
            "POBLACION",
            "PRITIL",
            "PULONG GUBAT",
            "SANTA CRUZ",
            "SANTA RITA",
            "TABANG",
            "TABE",
            "TIAONG",
            "TUKTUKAN",
          ],
        },
        HAGONOY: {
          barangay_list: [
            "ABULALAS",
            "CARILLO",
            "IBA",
            "IBA-IBAYO",
            "MERCADO",
            "PALAPAT",
            "PUGAD",
            "SAGRADA FAMILIA",
            "SAN AGUSTIN",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN",
            "SAN MIGUEL",
            "SAN NICOLAS",
            "SAN PABLO",
            "SAN PASCUAL",
            "SAN PEDRO",
            "SAN ROQUE",
            "SAN SEBASTIAN",
            "SANTA CRUZ",
            "SANTA ELENA",
            "SANTA MONICA",
            "SANTO NIÑO (POB.)",
            "SANTO ROSARIO",
            "TAMPOK",
            "TIBAGUIN",
          ],
        },
        "MALOLOS CITY": {
          barangay_list: [
            "ANILAO",
            "ATLAG",
            "BABATNIN",
            "BAGNA",
            "BAGONG BAYAN",
            "BALAYONG",
            "BALITE",
            "BANGKAL",
            "BARIHAN",
            "BULIHAN",
            "BUNGAHAN",
            "CAINGIN",
            "CALERO",
            "CALILIGAWAN",
            "CANALATE",
            "CANIOGAN",
            "CATMON",
            "COFRADIA",
            "DAKILA",
            "GUINHAWA",
            "LIGAS",
            "LIYANG",
            "LONGOS",
            "LOOK 1ST",
            "LOOK 2ND",
            "LUGAM",
            "MABOLO",
            "MAMBOG",
            "MASILE",
            "MATIMBO",
            "MOJON",
            "NAMAYAN",
            "NIUGAN",
            "PAMARAWAN",
            "PANASAHAN",
            "PINAGBAKAHAN",
            "SAN AGUSTIN",
            "SAN GABRIEL",
            "SAN JUAN",
            "SAN PABLO",
            "SAN VICENTE (POB.)",
            "SANTIAGO",
            "SANTISIMA TRINIDAD",
            "SANTO CRISTO",
            "SANTO NIÑO (POB.)",
            "SANTO ROSARIO (POB.)",
            "SANTOL",
            "SUMAPANG BATA",
            "SUMAPANG MATANDA",
            "TAAL",
            "TIKAY",
          ],
        },
        MARILAO: {
          barangay_list: [
            "ABANGAN NORTE",
            "ABANGAN SUR",
            "IBAYO",
            "LAMBAKIN",
            "LIAS",
            "LOMA DE GATO",
            "NAGBALON",
            "PATUBIG",
            "POBLACION I",
            "POBLACION II",
            "PRENZA I",
            "PRENZA II",
            "SANTA ROSA I",
            "SANTA ROSA II",
            "SAOG",
            "TABING ILOG",
          ],
        },
        "MEYCAUAYAN CITY": {
          barangay_list: [
            "BAGBAGUIN",
            "BAHAY PARE",
            "BANCAL",
            "BANGA",
            "BAYUGO",
            "CAINGIN",
            "CALVARIO",
            "CAMALIG",
            "GASAK (SAINT FRANCIS)",
            "HULO",
            "IBA",
            "LANGKA",
            "LAWA",
            "LIBTONG",
            "LIPUTAN",
            "LONGOS",
            "MALHACAN",
            "PAJO",
            "PANDAYAN",
            "PANTOC",
            "PEREZ",
            "POBLACION",
            "SALUYSOY",
            "TUGATOG",
            "UBIHAN",
            "ZAMORA",
          ],
        },
        NORZAGARAY: {
          barangay_list: [
            "BANGKAL",
            "BARAKA",
            "BIGTE",
            "BITUNGOL",
            "FRIENDSHIP VILLAGE RESOURCES",
            "MATICTIC",
            "MINUYAN",
            "PARTIDA",
            "PINAGTULAYAN",
            "POBLACION",
            "SAN LORENZO",
            "SAN MATEO",
            "TIGBE",
          ],
        },
        OBANDO: {
          barangay_list: [
            "BINUANGAN",
            "CATANGHALAN",
            "HULO",
            "LAWA",
            "PACO",
            "PAG-ASA (POB.)",
            "PALIWAS",
            "PANGHULO",
            "SALAMBAO",
            "SAN PASCUAL",
            "TAWIRAN",
          ],
        },
        PANDI: {
          barangay_list: [
            "BAGBAGUIN",
            "BAGONG BARRIO",
            "BAKA-BAKAHAN",
            "BUNSURAN I",
            "BUNSURAN II",
            "BUNSURAN III",
            "CACARONG BATA",
            "CACARONG MATANDA",
            "CUPANG",
            "MALIBONG BATA",
            "MALIBONG MATANDA",
            "MANATAL",
            "MAPULANG LUPA",
            "MASAGANA",
            "MASUSO",
            "PINAGKUARTELAN",
            "POBLACION",
            "REAL DE CACARONG",
            "SAN ROQUE",
            "SANTO NIÑO",
            "SILING BATA",
            "SILING MATANDA",
          ],
        },
        PAOMBONG: {
          barangay_list: [
            "BINAKOD",
            "KAPITANGAN",
            "MALUMOT",
            "MASUKOL",
            "PINALAGDAN",
            "POBLACION",
            "SAN ISIDRO I",
            "SAN ISIDRO II",
            "SAN JOSE",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA CRUZ",
            "SANTO NIÑO",
            "SANTO ROSARIO",
          ],
        },
        PLARIDEL: {
          barangay_list: [
            "AGNAYA",
            "BAGONG SILANG",
            "BANGA I",
            "BANGA II",
            "BINTOG",
            "BULIHAN",
            "CULIANIN",
            "DAMPOL",
            "LAGUNDI",
            "LALANGAN",
            "LUMANG BAYAN",
            "PARULAN",
            "POBLACION",
            "RUEDA",
            "SAN JOSE",
            "SANTA INES",
            "SANTO NIÑO",
            "SIPAT",
            "TABANG",
          ],
        },
        PULILAN: {
          barangay_list: [
            "BALATONG A",
            "BALATONG B",
            "CUTCOT",
            "DAMPOL I",
            "DAMPOL II-A",
            "DAMPOL II-B",
            "DULONG MALABON",
            "INAON",
            "LONGOS",
            "LUMBAC",
            "PALTAO",
            "PENABATAN",
            "POBLACION",
            "SANTA PEREGRINA",
            "SANTO CRISTO",
            "TAAL",
            "TABON",
            "TIBAG",
            "TINEJERO",
          ],
        },
        "SAN ILDEFONSO": {
          barangay_list: [
            "AKLE",
            "ALAGAO",
            "ANYATAM",
            "BAGONG BARRIO",
            "BASUIT",
            "BUBULONG MALAKI",
            "BUBULONG MUNTI",
            "BUHOL NA MANGGA",
            "BULUSUKAN",
            "CALASAG",
            "CALAWITAN",
            "CASALAT",
            "GABIHAN",
            "GARLANG",
            "LAPNIT",
            "MAASIM",
            "MAKAPILAPIL",
            "MALIPAMPANG",
            "MATAAS NA PARANG",
            "MATIMBUBONG",
            "NABAONG GARLANG",
            "PALAPALA",
            "PASONG BANGKAL",
            "PINAOD",
            "POBLACION",
            "PULONG TAMO",
            "SAN JUAN",
            "SANTA CATALINA BATA",
            "SANTA CATALINA MATANDA",
            "SAPANG DAYAP",
            "SAPANG PUTIK",
            "SAPANG PUTOL",
            "SUMANDIG",
            "TELEPATIO",
            "UMPUCAN",
            "UPIG",
          ],
        },
        "SAN JOSE DEL MONTE CITY": {
          barangay_list: [
            "ASSUMPTION",
            "BAGONG BUHAY",
            "BAGONG BUHAY II",
            "BAGONG BUHAY III",
            "CITRUS",
            "CIUDAD REAL",
            "DULONG BAYAN",
            "FATIMA",
            "FATIMA II",
            "FATIMA III",
            "FATIMA IV",
            "FATIMA V",
            "FRANCISCO HOMES-GUIJO",
            "FRANCISCO HOMES-MULAWIN",
            "FRANCISCO HOMES-NARRA",
            "FRANCISCO HOMES-YAKAL",
            "GAYA-GAYA",
            "GRACEVILLE",
            "GUMAOC CENTRAL",
            "GUMAOC EAST",
            "GUMAOC WEST",
            "KAYBANBAN",
            "KAYPIAN",
            "LAWANG PARI",
            "MAHARLIKA",
            "MINUYAN",
            "MINUYAN II",
            "MINUYAN III",
            "MINUYAN IV",
            "MINUYAN PROPER",
            "MINUYAN V",
            "MUZON",
            "PARADISE III",
            "POBLACION",
            "POBLACION I",
            "SAN ISIDRO",
            "SAN MANUEL",
            "SAN MARTIN",
            "SAN MARTIN II",
            "SAN MARTIN III",
            "SAN MARTIN IV",
            "SAN PEDRO",
            "SAN RAFAEL",
            "SAN RAFAEL I",
            "SAN RAFAEL III",
            "SAN RAFAEL IV",
            "SAN RAFAEL V",
            "SAN ROQUE",
            "SANTA CRUZ",
            "SANTA CRUZ II",
            "SANTA CRUZ III",
            "SANTA CRUZ IV",
            "SANTA CRUZ V",
            "SANTO CRISTO",
            "SANTO NIÑO",
            "SANTO NIÑO II",
            "SAPANG PALAY",
            "ST. MARTIN DE PORRES",
            "TUNGKONG MANGGA",
          ],
        },
        "SAN MIGUEL": {
          barangay_list: [
            "BAGONG PAG-ASA",
            "BAGONG SILANG",
            "BALAONG",
            "BALITE",
            "BANTOG",
            "BARDIAS",
            "BARITAN",
            "BATASAN BATA",
            "BATASAN MATANDA",
            "BIAK-NA-BATO",
            "BICLAT",
            "BUGA",
            "BULIRAN",
            "BULUALTO",
            "CALUMPANG",
            "CAMBIO",
            "CAMIAS",
            "ILOG-BULO",
            "KING KABAYO",
            "LABNE",
            "LAMBAKIN",
            "MAGMARALE",
            "MALIBAY",
            "MALIGAYA",
            "MANDILE",
            "MASALIPIT",
            "PACALAG",
            "PALIWASAN",
            "PARTIDA",
            "PINAMBARAN",
            "POBLACION",
            "PULONG BAYABAS",
            "PULONG DUHAT",
            "SACDALAN",
            "SALACOT",
            "SALANGAN",
            "SAN AGUSTIN",
            "SAN JOSE",
            "SAN JUAN",
            "SAN VICENTE",
            "SANTA INES",
            "SANTA LUCIA",
            "SANTA RITA BATA",
            "SANTA RITA MATANDA",
            "SAPANG",
            "SIBUL",
            "TARTARO",
            "TIBAGAN",
            "TIGPALAS",
          ],
        },
        "SAN RAFAEL": {
          barangay_list: [
            "BANCA-BANCA",
            "BMA-BALAGTAS",
            "CAINGIN",
            "CAPIHAN",
            "CORAL NA BATO",
            "CRUZ NA DAAN",
            "DAGAT-DAGATAN",
            "DILIMAN I",
            "DILIMAN II",
            "LIBIS",
            "LICO",
            "MAASIM",
            "MABALAS-BALAS",
            "MAGUINAO",
            "MARONGUILLO",
            "PACO",
            "PANSUMALOC",
            "PANTUBIG",
            "PASONG BANGKAL",
            "PASONG CALLOS",
            "PASONG INTSIK",
            "PINACPINACAN",
            "POBLACION",
            "PULO",
            "PULONG BAYABAS",
            "SALAPUNGAN",
            "SAMPALOC",
            "SAN AGUSTIN",
            "SAN ROQUE",
            "SAPANG PAHALANG",
            "TALACSAN",
            "TAMBUBONG",
            "TUKOD",
            "ULINGAO",
          ],
        },
        "SANTA MARIA": {
          barangay_list: [
            "BAGBAGUIN",
            "BALASING",
            "BUENAVISTA",
            "BULAC",
            "CAMANGYANAN",
            "CATMON",
            "CAY POMBO",
            "CAYSIO",
            "GUYONG",
            "LALAKHAN",
            "MAG-ASAWANG SAPA",
            "MAHABANG PARANG",
            "MANGGAHAN",
            "PARADA",
            "POBLACION",
            "PULONG BUHANGIN",
            "SAN GABRIEL",
            "SAN JOSE PATAG",
            "SAN VICENTE",
            "SANTA CLARA",
            "SANTA CRUZ",
            "SILANGAN",
            "TABING BAKOD",
            "TUMANA",
          ],
        },
      },
    },
    "NUEVA ECIJA": {
      municipality_list: {
        ALIAGA: {
          barangay_list: [
            "BETES",
            "BIBICLAT",
            "BUCOT",
            "LA PURISIMA",
            "MACABUCOD",
            "MAGSAYSAY",
            "PANTOC",
            "POBLACION CENTRO",
            "POBLACION EAST I",
            "POBLACION EAST II",
            "POBLACION WEST III",
            "POBLACION WEST IV",
            "SAN CARLOS",
            "SAN EMILIANO",
            "SAN EUSTACIO",
            "SAN FELIPE BATA",
            "SAN FELIPE MATANDA",
            "SAN JUAN",
            "SAN PABLO BATA",
            "SAN PABLO MATANDA",
            "SANTA MONICA",
            "SANTIAGO",
            "SANTO ROSARIO",
            "SANTO TOMAS",
            "SUNSON",
            "UMANGAN",
          ],
        },
        BONGABON: {
          barangay_list: [
            "ANTIPOLO",
            "ARIENDO",
            "BANTUG",
            "CALAANAN",
            "COMMERCIAL (POB.)",
            "CRUZ",
            "CURVA (J. TOMACRUZ)",
            "DIGMALA",
            "KAINGIN (POB.)",
            "LABI",
            "LARCON",
            "LUSOK",
            "MACABACLAY",
            "MAGTANGGOL (POB.)",
            "MANTILE (POB.)",
            "OLIVETE",
            "PALO MARIA (POB.)",
            "PESA",
            "RIZAL (POB.)",
            "SAMPALUCAN (POB.)",
            "SAN ROQUE (POB.)",
            "SANTOR",
            "SINIPIT (POB.)",
            "SISILANG NA LIGAYA (POB.)",
            "SOCIAL (POB.)",
            "TUGATUG",
            "TULAY NA BATO (POB.)",
            "VEGA",
          ],
        },
        "CABANATUAN CITY": {
          barangay_list: [
            "ADUAS CENTRO (ADUAS)",
            "ADUAS NORTE",
            "ADUAS SUR",
            "BAGONG BUHAY",
            "BAGONG SIKAT",
            "BAKERO",
            "BAKOD BAYAN",
            "BALITE",
            "BANGAD",
            "BANTUG BULALO",
            "BANTUG NORTE",
            "BARLIS",
            "BARRERA DISTRICT (POB.)",
            "BERNARDO DISTRICT (POB.)",
            "BITAS",
            "BONIFACIO DISTRICT (POB.)",
            "BULIRAN",
            "CAALIBANGBANGAN",
            "CABU",
            "CALAWAGAN (KALAWAGAN)",
            "CAMPO TINIO",
            "CARIDAD",
            "CAUDILLO",
            "CINCO-CINCO",
            "CITY SUPERMARKET (POB.)",
            "COMMUNAL",
            "CRUZ ROJA",
            "DAANG SARILE",
            "DALAMPANG",
            "DICARMA (POB.)",
            "DIMASALANG (POB.)",
            "DIONISIO S. GARCIA",
            "FATIMA (POB.)",
            "GENERAL LUNA (POB.)",
            "HERMOGENES C. CONCEPCION, SR.",
            "IBABAO BANA",
            "IMELDA DISTRICT",
            "ISLA (POB.)",
            "KALIKID NORTE",
            "KALIKID SUR",
            "KAPITAN PEPE (POB.)",
            "LAGARE",
            "LOURDES (MATUNGAL-TUNGAL)",
            "M. S. GARCIA",
            "MABINI EXTENSION",
            "MABINI HOMESITE",
            "MACATBONG",
            "MAGSAYSAY DISTRICT",
            "MAGSAYSAY SOUTH",
            "MARIA THERESA",
            "MATADERO (POB.)",
            "MAYAPYAP NORTE",
            "MAYAPYAP SUR",
            "MELOJAVILLA (POB.)",
            "NABAO (POB.)",
            "OBRERO",
            "PADRE BURGOS (POB.)",
            "PADRE CRISOSTOMO",
            "PAGAS",
            "PALAGAY",
            "PAMALDAN",
            "PANGATIAN",
            "PATALAC",
            "POLILIO",
            "PULA",
            "QUEZON DISTRICT (POB.)",
            "RIZDELIS (POB.)",
            "SAMON",
            "SAN ISIDRO",
            "SAN JOSEF NORTE",
            "SAN JOSEF SUR",
            "SAN JUAN POB. (ACOFA)",
            "SAN ROQUE NORTE",
            "SAN ROQUE SUR",
            "SANBERMICRISTI (POB.)",
            "SANGITAN",
            "SANGITAN EAST",
            "SANTA ARCADIA",
            "SANTO NIÑO",
            "SAPANG",
            "SUMACAB ESTE",
            "SUMACAB NORTE",
            "SUMACAB SOUTH",
            "TALIPAPA",
            "VALDEFUENTE",
            "VALLE CRUZ",
            "VIJANDRE DISTRICT (POB.)",
            "VILLA OFELIA-CARIDAD",
            "ZULUETA DISTRICT (POB.)",
          ],
        },
        CABIAO: {
          barangay_list: [
            "BAGONG BUHAY",
            "BAGONG SIKAT",
            "BAGONG SILANG",
            "CONCEPCION",
            "ENTABLADO",
            "MALIGAYA",
            "NATIVIDAD NORTH (POB.)",
            "NATIVIDAD SOUTH (POB.)",
            "PALASINAN",
            "POLILIO",
            "SAN ANTONIO",
            "SAN CARLOS",
            "SAN FERNANDO NORTE",
            "SAN FERNANDO SUR",
            "SAN GREGORIO",
            "SAN JUAN NORTH (POB.)",
            "SAN JUAN SOUTH (POB.)",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA INES",
            "SANTA ISABEL",
            "SANTA RITA",
            "SINIPIT",
          ],
        },
        CARRANGLAN: {
          barangay_list: [
            "BANTUG",
            "BUNGA",
            "BURGOS",
            "CAPINTALAN",
            "D. L. MAGLANOC POB. (BGY.III)",
            "F. C. OTIC POB. (BGY. II)",
            "G. S. ROSARIO POB. (BGY. IV)",
            "GENERAL LUNA",
            "JOSON (DIGIDIG)",
            "MINULI",
            "PIUT",
            "PUNCAN",
            "PUTLAN",
            "R.A.PADILLA (BALUARTE)",
            "SALAZAR",
            "SAN AGUSTIN",
            "T. L. PADILLA POB. (BGY. I)",
          ],
        },
        CUYAPO: {
          barangay_list: [
            "BALOY",
            "BAMBANABA",
            "BANTUG",
            "BENTIGAN",
            "BIBICLAT",
            "BONIFACIO",
            "BUED",
            "BULALA",
            "BURGOS",
            "CABATUAN",
            "CABILEO",
            "CACAPASAN",
            "CALANCUASAN NORTE",
            "CALANCUASAN SUR",
            "COLOSBOA",
            "COLUMBITIN",
            "CURVA",
            "DISTRICT I (POB. I)",
            "DISTRICT II (POB. II)",
            "DISTRICT IV (POB. IV)",
            "DISTRICT V (POB. V)",
            "DISTRICT VI (POB. VI)",
            "DISTRICT VII (POB. VII)",
            "DISTRICT VIII (POB. VIII)",
            "LANDIG",
            "LATAP",
            "LOOB",
            "LUNA",
            "MALBEG-PATALAN",
            "MALINENG",
            "MATINDEG",
            "MAYCABAN",
            "NACURALAN",
            "NAGMISAHAN",
            "PAITAN NORTE",
            "PAITAN SUR",
            "PIGLISAN",
            "PUGO",
            "RIZAL",
            "SABIT",
            "SALAGUSOG",
            "SAN ANTONIO",
            "SAN JOSE",
            "SAN JUAN",
            "SANTA CLARA",
            "SANTA CRUZ",
            "SINIMBAAN",
            "TAGTAGUMBAO",
            "TUTULOY",
            "UNGAB",
            "VILLAFLORES",
          ],
        },
        "GABALDON (BITULOK AND SABANI)": {
          barangay_list: [
            "BAGONG SIKAT",
            "BAGTING",
            "BANTUG",
            "BITULOK (NORTH POB.)",
            "BUGNAN",
            "CALABASA",
            "CAMACHILE",
            "CUYAPA",
            "LIGAYA",
            "MACASANDAL",
            "MALINAO",
            "PANTOC",
            "PINAMALISAN",
            "SAWMILL",
            "SOUTH POBLACION",
            "TAGUMPAY",
          ],
        },
        "GAPAN CITY": {
          barangay_list: [
            "BALANTE",
            "BAYANIHAN",
            "BULAK",
            "BUNGO",
            "KAPALANGAN",
            "MABUNGA",
            "MABURAK",
            "MAHIPON",
            "MAKABACLAY",
            "MALIMBA",
            "MANGINO",
            "MARELO",
            "PAMBUAN",
            "PARCUTELA",
            "PUTING TUBIG",
            "SAN LORENZO (POB.)",
            "SAN NICOLAS",
            "SAN ROQUE",
            "SAN VICENTE (POB.)",
            "SANTA CRUZ",
            "SANTO CRISTO NORTE",
            "SANTO CRISTO SUR",
            "SANTO NIÑO",
          ],
        },
        "GENERAL MAMERTO NATIVIDAD": {
          barangay_list: [
            "BALANGKARE NORTE",
            "BALANGKARE SUR",
            "BALARING",
            "BELEN",
            "BRAVO",
            "BUROL",
            "KABULIHAN",
            "MAG-ASAWANG SAMPALOC",
            "MANAROG",
            "MATAAS NA KAHOY",
            "PANACSAC",
            "PICALEON",
            "PINAHAN",
            "PLATERO",
            "POBLACION",
            "PULA",
            "PULONG SINGKAMAS",
            "SAPANG BATO",
            "TALABUTAB NORTE",
            "TALABUTAB SUR",
          ],
        },
        "GENERAL TINIO (PAPAYA)": {
          barangay_list: [
            "BAGO",
            "CONCEPCION",
            "NAZARETH",
            "PADOLINA",
            "PALALE",
            "PIAS",
            "POBLACION CENTRAL",
            "POBLACION EAST",
            "POBLACION WEST",
            "PULONG MATONG",
            "RIO CHICO",
            "SAMPAGUITA",
            "SAN PEDRO (POB.)",
          ],
        },
        GUIMBA: {
          barangay_list: [
            "AGCANO",
            "AYOS LOMBOY",
            "BACAYAO",
            "BAGONG BARRIO",
            "BALBALINO",
            "BALINGOG EAST",
            "BALINGOG WEST",
            "BANITAN",
            "BANTUG",
            "BULAKID",
            "BUNOL",
            "CABALLERO",
            "CABARUAN",
            "CAINGIN TABING ILOG",
            "CALEM",
            "CAMILING",
            "CARDINAL",
            "CASONGSONG",
            "CATIMON",
            "CAVITE",
            "CAWAYAN BUGTONG",
            "CONSUELO",
            "CULONG",
            "ESCANO",
            "FAIGAL",
            "GALVAN",
            "GUISET",
            "LAMORITO",
            "LENNEC",
            "MACAMIAS",
            "MACAPABELLAG",
            "MACATCATUIT",
            "MANACSAC",
            "MANGGANG MARIKIT",
            "MATURANOC",
            "MAYBUBON",
            "NAGLABRAHAN",
            "NAGPANDAYAN",
            "NARVACAN I",
            "NARVACAN II",
            "PACAC",
            "PARTIDA I",
            "PARTIDA II",
            "PASONG INCHIC",
            "SAINT JOHN DISTRICT (POB.)",
            "SAN AGUSTIN",
            "SAN ANDRES",
            "SAN BERNARDINO",
            "SAN MARCELINO",
            "SAN MIGUEL",
            "SAN RAFAEL",
            "SAN ROQUE",
            "SANTA ANA",
            "SANTA CRUZ",
            "SANTA LUCIA",
            "SANTA VERONICA DISTRICT (POB.)",
            "SANTO CRISTO DISTRICT (POB.)",
            "SARANAY DISTRICT (POB.)",
            "SINULATAN",
            "SUBOL",
            "TAMPAC I",
            "TAMPAC II AND III",
            "TRIALA",
            "YUSON",
          ],
        },
        JAEN: {
          barangay_list: [
            "CALABASA",
            "DAMPULAN (POB.)",
            "DON MARIANO MARCOS (POB.)",
            "HILERA",
            "IMBUNIA",
            "IMELDA POB. (DOÑA AURORA)",
            "LAMBAKIN",
            "LANGLA",
            "MAGSALISI",
            "MALABON-KAINGIN",
            "MARAWA",
            "NIYUGAN",
            "OCAMPO-RIVERA DISTRICT (POB.)",
            "PAKOL",
            "PAMACPACAN",
            "PINANGGAAN",
            "PUTLOD",
            "SAN JOSE",
            "SAN JOSEF (NABAO)",
            "SAN PABLO",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA RITA",
            "SANTO TOMAS NORTH",
            "SANTO TOMAS SOUTH",
            "SAPANG",
            "ULANIN-PITAK",
          ],
        },
        LAUR: {
          barangay_list: [
            "BARANGAY I (POB.)",
            "BARANGAY II (POB.)",
            "BARANGAY III (POB.)",
            "BARANGAY IV (POB.)",
            "BETANIA",
            "CANANTONG",
            "NAUZON",
            "PANGARULONG",
            "PINAGBAYANAN",
            "SAGANA",
            "SAN FELIPE",
            "SAN FERNANDO",
            "SAN ISIDRO",
            "SAN JOSEF",
            "SAN JUAN",
            "SAN VICENTE",
            "SICLONG",
          ],
        },
        LICAB: {
          barangay_list: [
            "AQUINO",
            "LINAO",
            "POBLACION NORTE",
            "POBLACION SUR",
            "SAN CASIMIRO",
            "SAN CRISTOBAL",
            "SAN JOSE",
            "SAN JUAN",
            "SANTA MARIA",
            "TABING ILOG",
            "VILLAROSA",
          ],
        },
        LLANERA: {
          barangay_list: [
            "A. BONIFACIO",
            "BAGUMBAYAN (POB.)",
            "BOSQUE",
            "CARIDAD NORTE",
            "CARIDAD SUR",
            "CASILE",
            "FLORIDA BLANCA",
            "GENERAL LUNA",
            "GENERAL RICARTE",
            "GOMEZ",
            "INANAMA",
            "LIGAYA",
            "MABINI",
            "MURCON",
            "PLARIDEL",
            "SAN FELIPE",
            "SAN FRANCISCO",
            "SAN NICOLAS",
            "SAN VICENTE",
            "SANTA BARBARA",
            "VICTORIA",
            "VILLA VINIEGAS",
          ],
        },
        LUPAO: {
          barangay_list: [
            "AGUPALO ESTE",
            "AGUPALO WESTE",
            "ALALAY CHICA",
            "ALALAY GRANDE",
            "BAGONG FLORES",
            "BALBALUNGAO",
            "BURGOS",
            "CORDERO",
            "J. U. TIENZO (ARIMAL)",
            "MAPANGPANG",
            "NAMULANDAYAN",
            "PARISTA",
            "POBLACION EAST",
            "POBLACION NORTH",
            "POBLACION SOUTH",
            "POBLACION WEST",
            "SALVACION I",
            "SALVACION II",
            "SAN ANTONIO ESTE",
            "SAN ANTONIO WESTE",
            "SAN ISIDRO",
            "SAN PEDRO",
            "SAN ROQUE",
            "SANTO DOMINGO",
          ],
        },
        NAMPICUAN: {
          barangay_list: [
            "ALEMANIA",
            "AMBASADOR ALZATE VILLAGE",
            "CABADUCAN EAST (POB.)",
            "CABADUCAN WEST (POB.)",
            "CABAWANGAN",
            "EAST CENTRAL POBLACION",
            "EDY",
            "ESTACION (POB.)",
            "MAELING",
            "MAYANTOC",
            "MEDICO",
            "MONIC",
            "NORTH POBLACION",
            "NORTHWEST POBLACION",
            "RECUERDO",
            "SOUTH CENTRAL POBLACION",
            "SOUTHEAST POBLACION",
            "SOUTHWEST POBLACION",
            "TONY",
            "WEST CENTRAL POBLACION",
            "WEST POBLACION",
          ],
        },
        "PALAYAN CITY": {
          barangay_list: [
            "ATATE",
            "AULO",
            "BAGONG BUHAY",
            "BO. MILITAR (FORT MAGSAYSAY)",
            "CABALLERO",
            "CAIMITO",
            "DOÑA JOSEFA",
            "GANADERIA",
            "IMELDA VALLEY",
            "LANGKA",
            "MALATE (POB.)",
            "MALIGAYA",
            "MANACNAC",
            "MAPAIT",
            "MARCOS VILLAGE",
            "POPOLON PAGAS",
            "SANTOLAN",
            "SAPANG BUHO",
            "SINGALAT",
          ],
        },
        PANTABANGAN: {
          barangay_list: [
            "CADACLAN",
            "CAMBITALA",
            "CONVERSION",
            "FATIMA",
            "GANDUZ",
            "LIBERTY",
            "MALBANG",
            "MARIKIT",
            "NAPON-NAPON",
            "POBLACION EAST",
            "POBLACION WEST",
            "SAMPALOC",
            "SAN JUAN",
            "VILLARICA",
          ],
        },
        PEÑARANDA: {
          barangay_list: [
            "CALLOS",
            "LAS PIÑAS",
            "POBLACION I",
            "POBLACION II",
            "POBLACION III",
            "POBLACION IV",
            "SAN JOSEF",
            "SAN MARIANO (MAUGAT)",
            "SANTO TOMAS",
            "SINASAJAN",
          ],
        },
        QUEZON: {
          barangay_list: [
            "BARANGAY I (POB.)",
            "BARANGAY II (POB.)",
            "BERTESE",
            "DOÑA LUCIA",
            "DULONG BAYAN",
            "ILOG BALIWAG",
            "PULONG BAHAY",
            "SAN ALEJANDRO",
            "SAN ANDRES I",
            "SAN ANDRES II",
            "SAN MANUEL",
            "SAN MIGUEL",
            "SANTA CLARA",
            "SANTA RITA",
            "SANTO CRISTO",
            "SANTO TOMAS FERIA",
          ],
        },
        RIZAL: {
          barangay_list: [
            "AGBANNAWAG",
            "AGLIPAY (CURVA)",
            "BICOS",
            "CABUCBUCAN",
            "CALAOCAN DISTRICT",
            "CANAAN EAST",
            "CANAAN WEST",
            "CASILAGAN",
            "DEL PILAR",
            "ESTRELLA",
            "GENERAL LUNA",
            "MACAPSING",
            "MALIGAYA",
            "PACO ROMAN",
            "PAG-ASA",
            "POBLACION CENTRAL",
            "POBLACION EAST",
            "POBLACION NORTE",
            "POBLACION SUR",
            "POBLACION WEST",
            "PORTAL",
            "SAN ESTEBAN",
            "SAN GREGORIO",
            "SANTA MONICA",
            "VILLA LABRADOR",
            "VILLA PARAISO",
          ],
        },
        "SAN ANTONIO": {
          barangay_list: [
            "BULIRAN",
            "CAMA JUAN",
            "JULO",
            "LAWANG KUPANG",
            "LUYOS",
            "MAUGAT",
            "PANABINGAN",
            "PAPAYA",
            "POBLACION",
            "SAN FRANCISCO",
            "SAN JOSE",
            "SAN MARIANO",
            "SANTA BARBARA",
            "SANTA CRUZ",
            "SANTO CRISTO",
            "TIKIW",
          ],
        },
        "SAN ISIDRO": {
          barangay_list: [
            "ALUA",
            "CALABA",
            "MALAPIT",
            "MANGGA",
            "POBLACION",
            "PULO",
            "SAN ROQUE",
            "SANTO CRISTO",
            "TABON",
          ],
        },
        "SAN JOSE CITY": {
          barangay_list: [
            "A. PASCUAL",
            "ABAR 2ND",
            "ABAR IST",
            "BAGONG SIKAT",
            "CAANAWAN",
            "CALAOCAN",
            "CAMANACSACAN",
            "CANUTO RAMOS POB. (DISTRICT III)",
            "CRISANTO SANCHEZ POB. (DISTRICT V)",
            "CULAYLAY",
            "DIZOL",
            "FERDINAND E. MARCOS POB. (DISTRICT II)",
            "KALIWANAGAN",
            "KITA-KITA",
            "MALASIN",
            "MANICLA",
            "PALESTINA",
            "PARANG MANGGA",
            "PINILI",
            "PORAIS",
            "RAFAEL RUEDA, SR. POB. (DISTRICT I)",
            "RAYMUNDO EUGENIO POB. (DISTRICT IV)",
            "SAN AGUSTIN",
            "SAN JUAN",
            "SAN MAURICIO",
            "SANTO NIÑO 1ST",
            "SANTO NIÑO 2ND",
            "SANTO NIÑO 3RD",
            "SANTO TOMAS",
            "SIBUT",
            "SINIPIT BUBON",
            "TABULAC",
            "TAYABO",
            "TONDOD",
            "TULAT",
            "VILLA FLORESCA",
            "VILLA JOSON (PARILLA)",
            "VILLA MARINA",
          ],
        },
        "SAN LEONARDO": {
          barangay_list: [
            "BONIFACIO DISTRICT (POB.)",
            "BURGOS DISTRICT (POB.)",
            "CASTELLANO",
            "DIVERSION",
            "MAGPAPALAYOC",
            "MALLORCA",
            "MAMBANGNAN",
            "NIEVES",
            "RIZAL DISTRICT (POB.)",
            "SAN ANTON",
            "SAN BARTOLOME (POB.)",
            "SAN ROQUE",
            "TABUATING",
            "TAGUMPAY",
            "TAMBO ADORABLE",
          ],
        },
        "SANTA ROSA": {
          barangay_list: [
            "AGUINALDO",
            "BERANG",
            "BURGOS",
            "COJUANGCO (POB.)",
            "DEL PILAR",
            "GOMEZ",
            "INSPECTOR",
            "ISLA",
            "LA FUENTE",
            "LIWAYWAY",
            "LOURDES",
            "LUNA",
            "MABINI",
            "MALACAÑANG",
            "MALIOLIO",
            "MAPALAD",
            "RAJAL CENTRO",
            "RAJAL NORTE",
            "RAJAL SUR",
            "RIZAL (POB.)",
            "SAN GREGORIO",
            "SAN ISIDRO",
            "SAN JOSEP",
            "SAN MARIANO",
            "SAN PEDRO",
            "SANTA TERESITA",
            "SANTO ROSARIO",
            "SAPSAP",
            "SOLEDAD",
            "TAGPOS",
            "TRAMO",
            "VALENZUELA (POB.)",
            "ZAMORA (POB.)",
          ],
        },
        "SANTO DOMINGO": {
          barangay_list: [
            "BALOC",
            "BUASAO",
            "BURGOS",
            "CABUGAO",
            "CASULUCAN",
            "COMITANG",
            "CONCEPCION",
            "DOLORES",
            "GENERAL LUNA",
            "HULO",
            "MABINI",
            "MALASIN",
            "MALAYA (POOK MALAYA)",
            "MALAYANTOC",
            "MAMBARAO",
            "POBLACION",
            "PULONG BULI",
            "SAGABA",
            "SAN AGUSTIN",
            "SAN FABIAN",
            "SAN FRANCISCO",
            "SAN PASCUAL",
            "SANTA RITA",
            "SANTO ROSARIO",
          ],
        },
        "SCIENCE CITY OF MUÑOZ": {
          barangay_list: [
            "BAGONG SIKAT",
            "BALANTE",
            "BANTUG",
            "BICAL",
            "CABISUCULAN",
            "CALABALABAAN",
            "CALISITAN",
            "CATALANACAN",
            "CURVA",
            "FRANZA",
            "GABALDON",
            "LABNEY",
            "LICAONG",
            "LINGLINGAY",
            "MAGTANGGOL",
            "MALIGAYA",
            "MANGANDINGAY",
            "MAPANGPANG",
            "MARAGOL",
            "MATINGKIS",
            "NAGLABRAHAN",
            "PALUSAPIS",
            "PANDALLA",
            "POBLACION EAST",
            "POBLACION NORTH",
            "POBLACION SOUTH",
            "POBLACION WEST",
            "RANG-AYAN",
            "RIZAL",
            "SAN ANDRES",
            "SAN ANTONIO",
            "SAN FELIPE",
            "SAPANG CAWAYAN",
            "VILLA CUIZON",
            "VILLA ISLA",
            "VILLA NATI",
            "VILLA SANTOS",
          ],
        },
        TALAVERA: {
          barangay_list: [
            "ANDAL ALINO (POB.)",
            "BAGONG SIKAT",
            "BAGONG SILANG",
            "BAKAL I",
            "BAKAL II",
            "BAKAL III",
            "BALUGA",
            "BANTUG",
            "BANTUG HACIENDA",
            "BANTUG HAMOG (BASANG HAMOG)",
            "BUGTONG NA BULI",
            "BULAC",
            "BURNAY",
            "CAANIPLAHAN",
            "CABUBULAONAN",
            "CALIPAHAN",
            "CAMPOS",
            "CAPUTICAN",
            "CASULUCAN ESTE",
            "COLLADO",
            "DIMASALANG NORTE",
            "DIMASALANG SUR",
            "DINARAYAT",
            "ESGUERRA DISTRICT (POB.)",
            "GULOD",
            "HOMESTEAD I",
            "HOMESTEAD II",
            "KINALANGUYAN",
            "LA TORRE",
            "LOMBOY",
            "MABUHAY",
            "MAESTRANG KIKAY (POB.)",
            "MAMANDIL",
            "MARCOS DISTRICT (POB.)",
            "MATINGKIS",
            "MINABUYOC",
            "PAG-ASA (POB.)",
            "PALUDPOD",
            "PANTOC BULAC",
            "PINAGPANAAN",
            "POBLACION SUR",
            "PULA",
            "PULONG SAN MIGUEL (POB.)",
            "PUROK MATIAS (POB.)",
            "SAMPALOC",
            "SAN MIGUEL NA MUNTI",
            "SAN PASCUAL",
            "SAN RICARDO",
            "SIBUL",
            "SICSICAN MATANDA",
            "TABACAO",
            "TAGAYTAY",
            "VALLE",
          ],
        },
        TALUGTUG: {
          barangay_list: [
            "ALULA",
            "BAYBAYABAS",
            "BUTED",
            "CABIANGAN",
            "CALISITAN",
            "CINENSE",
            "CULIAT",
            "MAASIN",
            "MAGSAYSAY (POB.)",
            "MAYAMOT I",
            "MAYAMOT II",
            "NANGABULAN",
            "OSMEÑA (POB.)",
            "PANGIT",
            "PATOLA",
            "QUEZON (POB.)",
            "QUIRINO (POB.)",
            "ROXAS (POB.)",
            "SAGUING",
            "SAMPALOC",
            "SANTA CATALINA",
            "SANTO DOMINGO",
            "SARINGAYA",
            "SAVERONA",
            "TANDOC",
            "TIBAG",
            "VILLA BOADO",
            "VILLA ROSARIO",
          ],
        },
        ZARAGOZA: {
          barangay_list: [
            "BATITANG",
            "CARMEN",
            "CONCEPCION",
            "DEL PILAR",
            "GENERAL LUNA",
            "H. ROMERO",
            "MACARSE",
            "MANAUL",
            "MAYAMOT",
            "PANTOC",
            "SAN ISIDRO",
            "SAN RAFAEL",
            "SAN VICENTE (POB.)",
            "SANTA CRUZ",
            "SANTA LUCIA OLD",
            "SANTA LUCIA YOUNG",
            "SANTO ROSARIO OLD",
            "SANTO ROSARIO YOUNG",
            "VALERIANA",
          ],
        },
      },
    },
    PAMPANGA: {
      municipality_list: {
        "ANGELES CITY": {
          barangay_list: [
            "AGAPITO DEL ROSARIO",
            "AMSIC",
            "ANUNAS",
            "BALIBAGO",
            "CAPAYA",
            "CLARO M. RECTO",
            "CUAYAN",
            "CUTCUT",
            "CUTUD",
            "LOURDES NORTH WEST",
            "LOURDES SUR",
            "LOURDES SUR EAST",
            "MALABANIAS",
            "MARGOT",
            "MINING",
            "NINOY AQUINO (MARISOL)",
            "PAMPANG",
            "PANDAN",
            "PULUNG CACUTUD",
            "PULUNG MARAGUL",
            "PULUNGBULU",
            "SALAPUNGAN",
            "SAN JOSE",
            "SAN NICOLAS",
            "SANTA TERESITA",
            "SANTA TRINIDAD",
            "SANTO CRISTO",
            "SANTO DOMINGO",
            "SANTO ROSARIO (POB.)",
            "SAPALIBUTAD",
            "SAPANGBATO",
            "TABUN",
            "VIRGEN DELOS REMEDIOS",
          ],
        },
        APALIT: {
          barangay_list: [
            "BALUCUC",
            "CALANTIPE",
            "CANSINALA",
            "CAPALANGAN",
            "COLGANTE",
            "PALIGUI",
            "SAMPALOC",
            "SAN JUAN (POB.)",
            "SAN VICENTE",
            "SUCAD",
            "SULIPAN",
            "TABUYUC (SANTO ROSARIO)",
          ],
        },
        ARAYAT: {
          barangay_list: [
            "ARENAS",
            "BALITI",
            "BATASAN",
            "BUENSUCESO",
            "CANDATING",
            "CUPANG (SANTA LUCIA)",
            "GATIAWIN",
            "GUEMASAN",
            "KALEDIAN (CAMBA)",
            "LA PAZ (TURU)",
            "LACMIT",
            "LACQUIOS",
            "MANGGA-CACUTUD",
            "MAPALAD",
            "MATAMO (SANTA LUCIA)",
            "PANLINLANG",
            "PARALAYA",
            "PLAZANG LUMA",
            "POBLACION",
            "SAN AGUSTIN NORTE",
            "SAN AGUSTIN SUR",
            "SAN ANTONIO",
            "SAN JOSE MESULO",
            "SAN JUAN BANO",
            "SAN MATEO",
            "SAN NICOLAS",
            "SAN ROQUE BITAS",
            "SANTO NIÑO TABUAN",
            "SUCLAYIN",
            "TELAPAYONG",
          ],
        },
        BACOLOR: {
          barangay_list: [
            "BALAS",
            "CABALANTIAN",
            "CABAMBANGAN (POB.)",
            "CABETICAN",
            "CALIBUTBUT",
            "CONCEPCION",
            "DOLORES",
            "DUAT",
            "MACABACLE",
            "MAGLIMAN",
            "MALIWALU",
            "MESALIPIT",
            "PARULOG",
            "POTRERO",
            "SAN ANTONIO",
            "SAN ISIDRO",
            "SAN VICENTE",
            "SANTA BARBARA",
            "SANTA INES",
            "TALBA",
            "TINAJERO",
          ],
        },
        CANDABA: {
          barangay_list: [
            "BAHAY PARE",
            "BAMBANG",
            "BARANGCA",
            "BARIT",
            "BUAS (POB.)",
            "CUAYANG BUGTONG",
            "DALAYAP",
            "DULONG ILOG",
            "GULAP",
            "LANANG",
            "LOURDES",
            "MAGUMBALI",
            "MANDASIG",
            "MANDILI",
            "MANGGA",
            "MAPANIQUI",
            "PALIGUI",
            "PANGCLARA",
            "PANSINAO",
            "PARALAYA (POB.)",
            "PASIG",
            "PESCADORES (POB.)",
            "PULONG GUBAT",
            "PULONG PALAZAN",
            "SALAPUNGAN",
            "SAN AGUSTIN (POB.)",
            "SANTO ROSARIO",
            "TAGULOD",
            "TALANG",
            "TENEJERO",
            "VIZAL SAN PABLO",
            "VIZAL SANTO CRISTO",
            "VIZAL SANTO NIÑO",
          ],
        },
        FLORIDABLANCA: {
          barangay_list: [
            "ANON",
            "APALIT",
            "BASA AIR BASE",
            "BENEDICTO",
            "BODEGA",
            "CABANGCALAN",
            "CALANTAS",
            "CARMENCITA",
            "CONSUELO",
            "DAMPE",
            "DEL CARMEN",
            "FORTUNA",
            "GUTAD",
            "MABICAL",
            "MALIGAYA",
            "MAWACAT",
            "NABUCLOD",
            "PABANLAG",
            "PAGUIRUAN",
            "PALMAYO",
            "PANDAGUIRIG",
            "POBLACION",
            "SAN ANTONIO",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN NICOLAS",
            "SAN PEDRO",
            "SAN RAMON",
            "SAN ROQUE",
            "SANTA MONICA",
            "SANTO ROSARIO (MALABO)",
            "SOLIB",
            "VALDEZ",
          ],
        },
        GUAGUA: {
          barangay_list: [
            "ASCOMO",
            "BANCAL",
            "JOSE ABAD SANTOS (SIRAN)",
            "LAMBAC",
            "MAGSAYSAY",
            "MAQUIAPO",
            "NATIVIDAD",
            "PLAZA BURGOS (POB.)",
            "PULUNGMASLE",
            "RIZAL",
            "SAN AGUSTIN",
            "SAN ANTONIO",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN",
            "SAN JUAN BAUTISTA",
            "SAN JUAN NEPOMUCENO",
            "SAN MATIAS",
            "SAN MIGUEL (BETIS)",
            "SAN NICOLAS 1ST",
            "SAN NICOLAS 2ND",
            "SAN PABLO",
            "SAN PEDRO",
            "SAN RAFAEL (DUCK ISLAND)",
            "SAN ROQUE",
            "SAN VICENTE (IBUS)",
            "SANTA FILOMENA (POB.)",
            "SANTA INES",
            "SANTA URSULA",
            "SANTO CRISTO",
            "SANTO NIÑO (POB.)",
          ],
        },
        LUBAO: {
          barangay_list: [
            "BALANTACAN",
            "BANCAL PUGAD",
            "BANCAL SINUBLI",
            "BARUYA (SAN RAFAEL)",
            "CALANGAIN",
            "CONCEPCION",
            "DE LA PAZ",
            "DEL CARMEN",
            "DON IGNACIO DIMSON",
            "LOURDES (LAUC PAU)",
            "PRADO SIONGCO",
            "REMEDIOS",
            "SAN AGUSTIN",
            "SAN ANTONIO",
            "SAN FRANCISCO",
            "SAN ISIDRO",
            "SAN JOSE APUNAN",
            "SAN JOSE GUMI",
            "SAN JUAN (POB.)",
            "SAN MATIAS",
            "SAN MIGUEL",
            "SAN NICOLAS 1ST (POB.)",
            "SAN NICOLAS 2ND",
            "SAN PABLO 1ST",
            "SAN PABLO 2ND",
            "SAN PEDRO PALCARANGAN",
            "SAN PEDRO SAUG",
            "SAN ROQUE ARBOL",
            "SAN ROQUE DAU",
            "SAN VICENTE",
            "SANTA BARBARA",
            "SANTA CATALINA",
            "SANTA CRUZ",
            "SANTA LUCIA (POB.)",
            "SANTA MARIA",
            "SANTA MONICA",
            "SANTA RITA",
            "SANTA TERESA 1ST",
            "SANTA TERESA 2ND",
            "SANTIAGO",
            "SANTO CRISTO",
            "SANTO DOMINGO",
            "SANTO NIÑO (PRADO ARUBA)",
            "SANTO TOMAS (POB.)",
          ],
        },
        "MABALACAT CITY": {
          barangay_list: [
            "ATLU-BOLA",
            "BICAL",
            "BUNDAGUL",
            "CACUTUD",
            "CALUMPANG",
            "CAMACHILES",
            "DAPDAP",
            "DAU",
            "DOLORES",
            "DUQUIT",
            "LAKANDULA",
            "MABIGA",
            "MACAPAGAL VILLAGE",
            "MAMATITANG",
            "MANGALIT",
            "MARCOS VILLAGE",
            "MAWAQUE",
            "PARALAYUNAN",
            "POBLACION",
            "SAN FRANCISCO",
            "SAN JOAQUIN",
            "SANTA INES",
            "SANTA MARIA",
            "SANTO ROSARIO",
            "SAPANG BALEN",
            "SAPANG BIABAS",
            "TABUN",
          ],
        },
        MACABEBE: {
          barangay_list: [
            "BATASAN",
            "CADUANG TETE",
            "CANDELARIA",
            "CASTULI",
            "CONSUELO",
            "DALAYAP",
            "MATAGUITI",
            "SAN ESTEBAN",
            "SAN FRANCISCO",
            "SAN GABRIEL (POB.)",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN",
            "SAN RAFAEL",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA CRUZ (POB.)",
            "SANTA LUTGARDA",
            "SANTA MARIA",
            "SANTA RITA (POB.)",
            "SANTO NIÑO",
            "SANTO ROSARIO (POB.)",
            "SAPLAD DAVID",
            "TACASAN",
            "TELACSAN",
          ],
        },
        MAGALANG: {
          barangay_list: [
            "AYALA",
            "BUCANAN",
            "CAMIAS",
            "DOLORES",
            "ESCALER",
            "LA PAZ",
            "NAVALING",
            "SAN AGUSTIN",
            "SAN ANTONIO",
            "SAN FRANCISO",
            "SAN ILDEFONSO",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN MIGUEL",
            "SAN NICOLAS 1ST (POB.)",
            "SAN NICOLAS 2ND",
            "SAN PABLO (POB.)",
            "SAN PEDRO I",
            "SAN PEDRO II",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA CRUZ (POB.)",
            "SANTA LUCIA",
            "SANTA MARIA",
            "SANTO NIÑO",
            "SANTO ROSARIO",
            "TURU",
          ],
        },
        MASANTOL: {
          barangay_list: [
            "ALAULI",
            "BAGANG",
            "BALIBAGO",
            "BEBE ANAC",
            "BEBE MATUA",
            "BULACUS",
            "CAMBASI",
            "MALAULI",
            "NIGUI",
            "PALIMPE",
            "PUTI",
            "SAGRADA (TIBAGIN)",
            "SAN AGUSTIN (CAINGIN)",
            "SAN ISIDRO ANAC",
            "SAN ISIDRO MATUA (POB.)",
            "SAN NICOLAS (POB.)",
            "SAN PEDRO",
            "SANTA CRUZ",
            "SANTA LUCIA ANAC (POB.)",
            "SANTA LUCIA MATUA",
            "SANTA LUCIA PAGUIBA",
            "SANTA LUCIA WAKAS",
            "SANTA MONICA (CAINGIN)",
            "SANTO NIÑO",
            "SAPANG KAWAYAN",
            "SUA",
          ],
        },
        MEXICO: {
          barangay_list: [
            "ACLI",
            "ANAO",
            "BALAS",
            "BUENAVISTA",
            "CAMUNING",
            "CAWAYAN",
            "CONCEPCION",
            "CULUBASA",
            "DIVISORIA",
            "DOLORES (PIRING)",
            "EDEN",
            "GANDUS",
            "LAGUNDI",
            "LAPUT",
            "LAUG",
            "MASAMAT",
            "MASANGSANG",
            "NUEVA VICTORIA",
            "PANDACAQUI",
            "PANGATLAN",
            "PANIPUAN",
            "PARIAN (POB.)",
            "SABANILLA",
            "SAN ANTONIO",
            "SAN CARLOS",
            "SAN JOSE MALINO",
            "SAN JOSE MATULID",
            "SAN JUAN",
            "SAN LORENZO",
            "SAN MIGUEL",
            "SAN NICOLAS",
            "SAN PABLO",
            "SAN PATRICIO",
            "SAN RAFAEL",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTA CRUZ",
            "SANTA MARIA",
            "SANTO DOMINGO",
            "SANTO ROSARIO",
            "SAPANG MAISAC",
            "SUCLABAN",
            "TANGLE (TANGLAY)",
          ],
        },
        MINALIN: {
          barangay_list: [
            "BULAC",
            "DAWE",
            "LOURDES",
            "MANIANGO",
            "SAN FRANCISCO 1ST",
            "SAN FRANCISCO 2ND",
            "SAN ISIDRO",
            "SAN NICOLAS (POB.)",
            "SAN PEDRO",
            "SANTA CATALINA",
            "SANTA MARIA",
            "SANTA RITA",
            "SANTO DOMINGO",
            "SANTO ROSARIO (POB.)",
            "SAPLAD",
          ],
        },
        PORAC: {
          barangay_list: [
            "BABO PANGULO",
            "BABO SACAN",
            "BALUBAD",
            "CALZADANG BAYU",
            "CAMIAS",
            "CANGATBA",
            "DIAZ",
            "DOLORES (HACIENDA DOLORES)",
            "INARARO (AETAS)",
            "JALUNG",
            "MANCATIAN",
            "MANIBAUG LIBUTAD",
            "MANIBAUG PARALAYA",
            "MANIBAUG PASIG",
            "MANUALI",
            "MITLA PROPER",
            "PALAT",
            "PIAS",
            "PIO",
            "PLANAS",
            "POBLACION",
            "PULONG SANTOL",
            "SALU",
            "SAN JOSE MITLA",
            "SANTA CRUZ",
            "SAPANG UWAK (AETAS)",
            "SEPUNG BULAUN",
            "SINURA",
            "VILLA MARIA (AETAS)",
          ],
        },
        "SAN FERNANDO CITY": {
          barangay_list: [
            "ALASAS",
            "BALITI",
            "BULAON",
            "CALULUT",
            "DEL CARMEN",
            "DEL PILAR",
            "DEL ROSARIO",
            "DELA PAZ NORTE",
            "DELA PAZ SUR",
            "DOLORES",
            "JULIANA",
            "LARA",
            "LOURDES",
            "MAGLIMAN",
            "MAIMPIS",
            "MALINO",
            "MALPITIC",
            "PANDARAS",
            "PANIPUAN",
            "PULUNG BULU",
            "QUEBIAUAN",
            "SAGUIN",
            "SAN AGUSTIN",
            "SAN FELIPE",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN",
            "SAN NICOLAS",
            "SAN PEDRO",
            "SANTA LUCIA",
            "SANTA TERESITA",
            "SANTO NIÑO",
            "SANTO ROSARIO (POB.)",
            "SINDALAN",
            "TELABASTAGAN",
          ],
        },
        "SAN LUIS": {
          barangay_list: [
            "SAN AGUSTIN",
            "SAN CARLOS",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN",
            "SAN NICOLAS",
            "SAN ROQUE",
            "SAN SEBASTIAN",
            "SANTA CATALINA",
            "SANTA CRUZ PAMBILOG",
            "SANTA CRUZ POBLACION",
            "SANTA LUCIA",
            "SANTA MONICA",
            "SANTA RITA",
            "SANTO NIÑO",
            "SANTO ROSARIO",
            "SANTO TOMAS",
          ],
        },
        "SAN SIMON": {
          barangay_list: [
            "CONCEPCION",
            "DE LA PAZ",
            "SAN AGUSTIN",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JUAN (POB.)",
            "SAN MIGUEL",
            "SAN NICOLAS",
            "SAN PABLO LIBUTAD",
            "SAN PABLO PROPER",
            "SAN PEDRO",
            "SANTA CRUZ",
            "SANTA MONICA",
            "SANTO NIÑO",
          ],
        },
        "SANTA ANA": {
          barangay_list: [
            "SAN AGUSTIN",
            "SAN BARTOLOME",
            "SAN ISIDRO",
            "SAN JOAQUIN (POB.)",
            "SAN JOSE",
            "SAN JUAN",
            "SAN NICOLAS",
            "SAN PABLO",
            "SAN PEDRO",
            "SAN ROQUE",
            "SANTA LUCIA",
            "SANTA MARIA",
            "SANTIAGO",
            "SANTO ROSARIO",
          ],
        },
        "SANTA RITA": {
          barangay_list: [
            "BECURAN",
            "DILA-DILA",
            "SAN AGUSTIN",
            "SAN BASILIO",
            "SAN ISIDRO",
            "SAN JOSE (POB.)",
            "SAN JUAN",
            "SAN MATIAS",
            "SAN VICENTE",
            "SANTA MONICA",
          ],
        },
        "SANTO TOMAS": {
          barangay_list: [
            "MORAS DE LA PAZ",
            "POBLACION",
            "SAN BARTOLOME",
            "SAN MATIAS",
            "SAN VICENTE",
            "SANTO ROSARIO (PAU)",
            "SAPA (SANTO NIÑO)",
          ],
        },
        "SASMUAN (SEXMOAN)": {
          barangay_list: [
            "BATANG 1ST",
            "BATANG 2ND",
            "MABUANBUAN",
            "MALUSAC",
            "SABITANAN",
            "SAN ANTONIO",
            "SAN NICOLAS 1ST",
            "SAN NICOLAS 2ND",
            "SAN PEDRO",
            "SANTA LUCIA (POB.)",
            "SANTA MONICA",
            "SANTO TOMAS",
          ],
        },
      },
    },
    TARLAC: {
      municipality_list: {
        ANAO: {
          barangay_list: [
            "BAGUINDOC (BAGUINLOC)",
            "BANTOG",
            "CAMPOS",
            "CARMEN",
            "CASILI",
            "DON RAMON",
            "HERNANDO",
            "POBLACION",
            "RIZAL",
            "SAN FRANCISCO EAST",
            "SAN FRANCISCO WEST",
            "SAN JOSE NORTH",
            "SAN JOSE SOUTH",
            "SAN JUAN",
            "SAN ROQUE",
            "SANTO DOMINGO",
            "SINENSE",
            "SUAVERDEZ",
          ],
        },
        BAMBAN: {
          barangay_list: [
            "ANUPUL",
            "BANABA",
            "BANGCU",
            "CULUBASA",
            "DELA CRUZ",
            "LA PAZ",
            "LOURDES",
            "MALONZO",
            "SAN NICOLAS (POB.)",
            "SAN PEDRO",
            "SAN RAFAEL",
            "SAN ROQUE",
            "SAN VICENTE",
            "SANTO NIÑO",
            "VIRGEN DE LOS REMEDIOS (PACALCAL)",
          ],
        },
        CAMILING: {
          barangay_list: [
            "ANOLING 1ST",
            "ANOLING 2ND",
            "ANOLING 3RD",
            "BACABAC",
            "BACSAY",
            "BANCAY 1ST",
            "BANCAY 2ND",
            "BILAD",
            "BIRBIRA",
            "BOBON 1ST",
            "BOBON 2ND",
            "BOBON CAAROSIPAN",
            "CABANABAAN",
            "CACAMILINGAN NORTE",
            "CACAMILINGAN SUR",
            "CANIAG",
            "CARAEL",
            "CAYAOAN",
            "CAYASAN",
            "FLORIDA",
            "LASONG",
            "LIBUEG",
            "MALACAMPA",
            "MANAKEM",
            "MANUPEG",
            "MARAWI",
            "MATUBOG",
            "NAGRAMBACAN",
            "NAGSERIALAN",
            "PALIMBO PROPER",
            "PALIMBO-CAAROSIPAN",
            "PAO 1ST",
            "PAO 2ND",
            "PAO 3RD",
            "PAPAAC",
            "PINDANGAN 1ST",
            "PINDANGAN 2ND",
            "POBLACION A",
            "POBLACION B",
            "POBLACION C",
            "POBLACION D",
            "POBLACION E",
            "POBLACION F",
            "POBLACION G",
            "POBLACION H",
            "POBLACION I",
            "POBLACION J",
            "SANTA MARIA",
            "SAWAT",
            "SINILIAN 1ST",
            "SINILIAN 2ND",
            "SINILIAN 3RD",
            "SINILIAN CACALIBOSOAN",
            "SINULATAN 1ST",
            "SINULATAN 2ND",
            "SURGUI 1ST",
            "SURGUI 2ND",
            "SURGUI 3RD",
            "TAMBUGAN",
            "TELBANG",
            "TUEC",
          ],
        },
        CAPAS: {
          barangay_list: [
            "ARANGUREN",
            "BUENO",
            "CRISTO REY",
            "CUBCUB (POB.)",
            "CUTCUT 1ST",
            "CUTCUT 2ND",
            "DOLORES",
            "ESTRADA (CALINGCUAN)",
            "LAWY",
            "MANGA",
            "MANLAPIG",
            "MARUGLU",
            "O'DONNELL",
            "SANTA JULIANA",
            "SANTA LUCIA",
            "SANTA RITA",
            "SANTO DOMINGO 1ST",
            "SANTO DOMINGO 2ND",
            "SANTO ROSARIO",
            "TALAGA",
          ],
        },
        "CITY OF TARLAC": {
          barangay_list: [
            "AGUSO",
            "ALVINDIA SEGUNDO",
            "AMUCAO",
            "ARMENIA",
            "ASTURIAS",
            "ATIOC",
            "BALANTI",
            "BALETE",
            "BALIBAGO I",
            "BALIBAGO II",
            "BALINGCANAWAY",
            "BANABA",
            "BANTOG",
            "BARAS-BARAS",
            "BATANG-BATANG",
            "BINAUGANAN",
            "BORA",
            "BUENAVISTA",
            "BUHILIT (BUBULIT)",
            "BUROT",
            "CALINGCUAN",
            "CAPEHAN",
            "CARANGIAN",
            "CARE",
            "CENTRAL",
            "CULIPAT",
            "CUT-CUT I",
            "CUT-CUT II",
            "DALAYAP",
            "DELA PAZ",
            "DOLORES",
            "LAOANG",
            "LIGTASAN",
            "LOURDES",
            "MABINI",
            "MALIGAYA",
            "MALIWALO",
            "MAPALACSIAO",
            "MAPALAD",
            "MATADERO",
            "MATATALAIB",
            "PARAISO",
            "POBLACION",
            "SALAPUNGAN",
            "SAN CARLOS",
            "SAN FRANCISCO",
            "SAN ISIDRO",
            "SAN JOSE",
            "SAN JOSE DE URQUICO",
            "SAN JUAN DE MATA",
            "SAN LUIS",
            "SAN MANUEL",
            "SAN MIGUEL",
            "SAN NICOLAS",
            "SAN PABLO",
            "SAN PASCUAL",
            "SAN RAFAEL",
            "SAN ROQUE",
            "SAN SEBASTIAN",
            "SAN VICENTE",
            "SANTA CRUZ (ALVINDIA PRIMERO)",
            "SANTA MARIA",
            "SANTO CRISTO",
            "SANTO DOMINGO",
            "SANTO NIÑO",
            "SAPANG MARAGUL",
            "SAPANG TAGALOG",
            "SEPUNG CALZADA",
            "SINAIT",
            "SUIZO",
            "TARIJI",
            "TIBAG",
            "TIBAGAN",
            "TRINIDAD (TRINIDAD PRIMERO)",
            "UNGOT",
            "VILLA BACOLOR",
          ],
        },
        CONCEPCION: {
          barangay_list: [
            "ALFONSO",
            "BALUTU",
            "CAFE",
            "CALIUS GUECO",
            "CALULUAN",
            "CASTILLO",
            "CORAZON DE JESUS",
            "CULATINGAN",
            "DUNGAN",
            "DUTUNG-A-MATAS",
            "GREEN VILLAGE",
            "LILIBANGAN",
            "MABILOG",
            "MAGAO",
            "MALUPA",
            "MINANE",
            "PANALICSIAN (PANALICSICAN)",
            "PANDO",
            "PARANG",
            "PARULUNG",
            "PITABUNAN",
            "SAN AGUSTIN (MURCIA)",
            "SAN ANTONIO",
            "SAN BARTOLOME",
            "SAN FRANCISCO",
            "SAN ISIDRO (ALMENDRAS)",
            "SAN JOSE (POB.)",
            "SAN JUAN (CASTRO)",
            "SAN MARTIN",
            "SAN NICOLAS (POB.)",
            "SAN NICOLAS BALAS",
            "SAN VICENTE (CALUIS/COBRA)",
            "SANTA CRUZ",
            "SANTA MARIA",
            "SANTA MONICA",
            "SANTA RITA",
            "SANTA ROSA",
            "SANTIAGO",
            "SANTO CRISTO",
            "SANTO NIÑO",
            "SANTO ROSARIO (MAGUNTING)",
            "TALIMUNDUC MARIMLA",
            "TALIMUNDUC SAN MIGUEL",
            "TELABANCA",
            "TINANG",
          ],
        },
        GERONA: {
          barangay_list: [
            "ABAGON",
            "AMACALAN",
            "APSAYAN",
            "AYSON",
            "BAWA",
            "BUENLAG",
            "BULARIT",
            "CALAYAAN",
            "CARBONEL",
            "CARDONA",
            "CATURAY",
            "DANZO",
            "DICOLOR",
            "DON BASILIO",
            "LUNA",
            "MABINI",
            "MAGASPAC",
            "MALAYEP",
            "MATAPITAP",
            "MATAYUMCAB",
            "NEW SALEM",
            "OLOYBUAYA",
            "PADAPADA",
            "PARSOLINGAN",
            "PINASLING (PINASUNG)",
            "PLASTADO",
            "POBLACION 1",
            "POBLACION 2",
            "POBLACION 3",
            "QUEZON",
            "RIZAL",
            "SALAPUNGAN",
            "SAN AGUSTIN",
            "SAN ANTONIO",
            "SAN BARTOLOME",
            "SAN JOSE",
            "SANTA LUCIA",
            "SANTIAGO",
            "SEMBRANO",
            "SINGAT",
            "SULIPA",
            "TAGUMBAO",
            "TANGCARAN",
            "VILLA PAZ",
          ],
        },
        "LA PAZ": {
          barangay_list: [
            "BALANOY",
            "BANTOG-CARICUTAN",
            "CARAMUTAN",
            "CAUT",
            "COMILLAS",
            "DUMARAIS",
            "GUEVARRA",
            "KAPANIKIAN",
            "LA PURISIMA",
            "LARA",
            "LAUNGCUPANG",
            "LOMBOY",
            "MACALONG",
            "MATAYUMTAYUM",
            "MAYANG",
            "MOTRICO",
            "PALUDPUD",
            "RIZAL",
            "SAN ISIDRO (POB.)",
            "SAN ROQUE (POB.)",
            "SIERRA",
          ],
        },
        MAYANTOC: {
          barangay_list: [
            "AMBALINGIT",
            "BAYBAYAOAS",
            "BIGBIGA",
            "BINBINACA",
            "CALABTANGAN",
            "CAOCAOAYAN",
            "CARABAOAN",
            "CUBCUB",
            "GAYONGGAYONG",
            "GOSSOOD",
            "LABNEY",
            "MAMONIT",
            "MANINIOG",
            "MAPANDAN",
            "NAMBALAN",
            "PEDRO L. QUINES",
            "PITOMBAYOG",
            "POBLACION NORTE",
            "POBLACION SUR",
            "ROTROTTOOC",
            "SAN BARTOLOME",
            "SAN JOSE",
            "TALDIAPAN",
            "TANGCARANG",
          ],
        },
        MONCADA: {
          barangay_list: [
            "ABLANG-SAPANG",
            "ARINGIN",
            "ATENCIO",
            "BANAOANG EAST",
            "BANAOANG WEST",
            "BAQUERO NORTE",
            "BAQUERO SUR",
            "BURGOS",
            "CALAMAY",
            "CALAPAN",
            "CAMANGAAN EAST",
            "CAMANGAAN WEST",
            "CAMPOSANTO 1 - NORTE",
            "CAMPOSANTO 1 - SUR",
            "CAMPOSANTO 2",
            "CAPAOAYAN",
            "LAPSING",
            "MABINI",
            "MALUAC",
            "POBLACION 1",
            "POBLACION 2",
            "POBLACION 3",
            "POBLACION 4",
            "RIZAL",
            "SAN JUAN",
            "SAN JULIAN",
            "SAN LEON",
            "SAN PEDRO",
            "SAN ROQUE",
            "SANTA LUCIA EAST",
            "SANTA LUCIA WEST",
            "SANTA MARIA",
            "SANTA MONICA",
            "TOLEGA NORTE",
            "TOLEGA SUR",
            "TUBECTUBANG",
            "VILLA",
          ],
        },
        PANIQUI: {
          barangay_list: [
            "ABOGADO",
            "ACOCOLAO",
            "ADUAS",
            "APULID",
            "BALAOANG",
            "BARANG (BORANG)",
            "BRILLANTE",
            "BURGOS",
            "CABAYAOASAN",
            "CANAN",
            "CARINO",
            "CAYANGA",
            "COLIBANGBANG",
            "CORAL",
            "DAPDAP",
            "ESTACION",
            "MABILANG",
            "MANAOIS",
            "MATALAPITAP",
            "NAGMISAAN",
            "NANCAMARINAN",
            "NIPACO",
            "PATALAN",
            "POBLACION NORTE",
            "POBLACION SUR",
            "RANG-AYAN",
            "SALUMAGUE",
            "SAMPUT",
            "SAN CARLOS",
            "SAN ISIDRO",
            "SAN JUAN DE MILLA",
            "SANTA INES",
            "SINIGPIT",
            "TABLANG",
            "VENTENILLA",
          ],
        },
        PURA: {
          barangay_list: [
            "BALITE",
            "BUENAVISTA",
            "CADANGLAAN",
            "ESTIPONA",
            "LINAO",
            "MAASIN",
            "MATINDEG",
            "MAUNGIB",
            "NAYA",
            "NILASIN 1ST",
            "NILASIN 2ND",
            "POBLACION 1",
            "POBLACION 2",
            "POBLACION 3",
            "POROC",
            "SINGAT",
          ],
        },
        RAMOS: {
          barangay_list: [
            "CORAL-ILOCO",
            "GUITEB",
            "PANCE",
            "POBLACION CENTER",
            "POBLACION NORTH",
            "POBLACION SOUTH",
            "SAN JUAN",
            "SAN RAYMUNDO",
            "TOLEDO",
          ],
        },
        "SAN CLEMENTE": {
          barangay_list: [
            "BALLOC",
            "BAMBAN",
            "CASIPO",
            "CATAGUDINGAN",
            "DALDALAYAP",
            "DOCLONG 1",
            "DOCLONG 2",
            "MAASIN",
            "NAGSABARAN",
            "PIT-AO",
            "POBLACION NORTE",
            "POBLACION SUR",
          ],
        },
        "SAN JOSE": {
          barangay_list: [
            "BURGOS",
            "DAVID",
            "IBA",
            "LABNEY",
            "LAWACAMULAG",
            "LUBIGAN",
            "MAAMOT",
            "MABABANABA",
            "MORIONES",
            "PAO",
            "SAN JUAN DE VALDEZ",
            "SULA",
            "VILLA AGLIPAY",
          ],
        },
        "SAN MANUEL": {
          barangay_list: [
            "COLUBOT",
            "LANAT",
            "LEGASPI",
            "MANGANDINGAY",
            "MATARANNOC",
            "PACPACO",
            "POBLACION",
            "SALCEDO",
            "SAN AGUSTIN",
            "SAN FELIPE",
            "SAN JACINTO",
            "SAN MIGUEL",
            "SAN NARCISO",
            "SAN VICENTE",
            "SANTA MARIA",
          ],
        },
        "SANTA IGNACIA": {
          barangay_list: [
            "BALDIOS",
            "BOTBOTONES",
            "CAANAMONGAN",
            "CABARUAN",
            "CABUGBUGAN",
            "CADULDULAOAN",
            "CALIPAYAN",
            "MACAGUING",
            "NAMBALAN",
            "PADAPADA",
            "PILPILA",
            "PINPINAS",
            "POBLACION EAST",
            "POBLACION WEST",
            "PUGO-CECILIO",
            "SAN FRANCISCO",
            "SAN SOTERO",
            "SAN VICENTE",
            "SANTA INES CENTRO",
            "SANTA INES EAST",
            "SANTA INES WEST",
            "TAGUIPORO",
            "TIMMAGUAB",
            "VARGAS",
          ],
        },
        VICTORIA: {
          barangay_list: [
            "BACULONG",
            "BALAYANG",
            "BALBALOTO",
            "BANGAR",
            "BANTOG",
            "BATANGBATANG",
            "BULO",
            "CABULUAN",
            "CALIBUNGAN",
            "CANAREM",
            "CRUZ",
            "LALAPAC",
            "MALUID",
            "MANGOLAGO",
            "MASALASA",
            "PALACPALAC",
            "SAN AGUSTIN",
            "SAN ANDRES",
            "SAN FERNANDO (POB.)",
            "SAN FRANCISCO",
            "SAN GAVINO (POB.)",
            "SAN JACINTO",
            "SAN NICOLAS (POB.)",
            "SAN VICENTE",
            "SANTA BARBARA",
            "SANTA LUCIA (POB.)",
          ],
        },
      },
    },
    ZAMBALES: {
      municipality_list: {
        BOTOLAN: {
          barangay_list: [
            "BANCAL",
            "BANGAN",
            "BATONLAPOC",
            "BELBEL",
            "BENEG",
            "BINUCLUTAN",
            "BURGOS",
            "CABATUAN",
            "CAPAYAWAN",
            "CARAEL",
            "DANACBUNGA",
            "MAGUISGUIS",
            "MALOMBOY",
            "MAMBOG",
            "MORAZA",
            "NACOLCOL",
            "OWAOG-NIBLOC",
            "PACO (POB.)",
            "PALIS",
            "PANAN",
            "PAREL",
            "PAUDPOD",
            "POONBATO",
            "PORAC",
            "SAN ISIDRO",
            "SAN JUAN",
            "SAN MIGUEL",
            "SANTIAGO",
            "TAMPO (POB.)",
            "TAUGTOG",
            "VILLAR",
          ],
        },
        CABANGAN: {
          barangay_list: [
            "ANONANG",
            "APO-APO",
            "AREW",
            "BANUAMBAYO (POB.)",
            "CADMANG-RESERVA",
            "CAMILING (CAMIING)",
            "CASABAAN",
            "DEL CARMEN (POB.)",
            "DOLORES (POB.)",
            "FELMIDA-DIAZ",
            "LAOAG",
            "LOMBOY",
            "LONGOS",
            "MABANGLIT",
            "NEW SAN JUAN",
            "SAN ANTONIO",
            "SAN ISIDRO",
            "SAN JUAN (POB.)",
            "SAN RAFAEL",
            "SANTA RITA",
            "SANTO NIÑO",
            "TONDO",
          ],
        },
        CANDELARIA: {
          barangay_list: [
            "BABANCAL",
            "BINABALIAN",
            "CATOL",
            "DAMPAY",
            "LAUIS",
            "LIBERTADOR",
            "MALABON (SAN ROQUE)",
            "MALIMANGA",
            "PAMIBIAN",
            "PANAYONAN",
            "PINAGREALAN",
            "POBLACION",
            "SINABACAN",
            "TAPOSO",
            "UACON",
            "YAMOT",
          ],
        },
        CASTILLEJOS: {
          barangay_list: [
            "BALAYBAY",
            "BUENAVISTA",
            "DEL PILAR",
            "LOOC",
            "MAGSAYSAY",
            "NAGBAYAN",
            "NAGBUNGA",
            "SAN AGUSTIN",
            "SAN JOSE (POB.)",
            "SAN JUAN (POB.)",
            "SAN NICOLAS",
            "SAN PABLO (POB.)",
            "SAN ROQUE",
            "SANTA MARIA",
          ],
        },
        IBA: {
          barangay_list: [
            "AMUNGAN",
            "BANGANTALINGA",
            "DIRITA-BALOGUEN",
            "LIPAY-DINGIN-PANIBUATAN",
            "PALANGINAN (PALANGUINAN-TAMBAK)",
            "SAN AGUSTIN",
            "SANTA BARBARA",
            "SANTO ROSARIO",
            "ZONE 1 POB. (LIBABA)",
            "ZONE 2 POB. (AYPA)",
            "ZONE 3 POB. (BOTLAY)",
            "ZONE 4 POB. (SAGAPAN)",
            "ZONE 5 POB. (BANO)",
            "ZONE 6 POB. (BAYTAN)",
          ],
        },
        MASINLOC: {
          barangay_list: [
            "BALOGANON",
            "BAMBAN",
            "BANI",
            "COLLAT",
            "INHOBOL",
            "NORTH POBLACION",
            "SAN LORENZO",
            "SAN SALVADOR",
            "SANTA RITA",
            "SANTO ROSARIO",
            "SOUTH POBLACION",
            "TALTAL",
            "TAPUAC",
          ],
        },
        "OLONGAPO CITY": {
          barangay_list: [
            "ASINAN",
            "BANICAIN",
            "BARRETO",
            "EAST BAJAC-BAJAC",
            "EAST TAPINAC",
            "GORDON HEIGHTS",
            "KALAKLAN",
            "MABAYUAN",
            "NEW CABALAN",
            "NEW ILALIM",
            "NEW KABABAE",
            "NEW KALALAKE",
            "OLD CABALAN",
            "PAG-ASA",
            "SANTA RITA",
            "WEST BAJAC-BAJAC",
            "WEST TAPINAC",
          ],
        },
        PALAUIG: {
          barangay_list: [
            "ALWA",
            "BATO",
            "BULAWEN",
            "CAUYAN",
            "EAST POBLACION",
            "GARRETA",
            "LIBABA",
            "LIOZON",
            "LIPAY",
            "LOCLOC",
            "MACARANG",
            "MAGALAWA",
            "PANGOLINGAN",
            "SALAZA",
            "SAN JUAN",
            "SANTO NIÑO",
            "SANTO TOMAS",
            "TITION (SAN VICENTE)",
            "WEST POBLACION",
          ],
        },
        "SAN ANTONIO": {
          barangay_list: [
            "ANGELES",
            "ANTIPOLO (POB.)",
            "BURGOS (POB.)",
            "EAST DIRITA",
            "LUNA (POB.)",
            "PUNDAQUIT",
            "RIZAL",
            "SAN ESTEBAN",
            "SAN GREGORIO (POB.)",
            "SAN JUAN (POB.)",
            "SAN MIGUEL",
            "SAN NICOLAS (POB.)",
            "SANTIAGO",
            "WEST DIRITA",
          ],
        },
        "SAN FELIPE": {
          barangay_list: [
            "AMAGNA (POB.)",
            "APOSTOL (POB.)",
            "BALINCAGUING",
            "FARAÑAL (POB.)",
            "FERIA (POB.)",
            "MALOMA",
            "MANGLICMOT (POB.)",
            "ROSETE (POB.)",
            "SAN RAFAEL",
            "SANTO NIÑO",
            "SINDOL",
          ],
        },
        "SAN MARCELINO": {
          barangay_list: [
            "AGLAO",
            "BUHAWEN",
            "BURGOS (POB.)",
            "CENTRAL (POB.)",
            "CONSUELO NORTE",
            "CONSUELO SUR (POB.)",
            "LA PAZ (POB.)",
            "LAOAG",
            "LINASIN",
            "LINUSUNGAN",
            "LUCERO (POB.)",
            "NAGBUNGA",
            "RABANES",
            "RIZAL (POB.)",
            "SAN GUILLERMO (POB.)",
            "SAN ISIDRO (POB.)",
            "SAN RAFAEL",
            "SANTA FE",
          ],
        },
        "SAN NARCISO": {
          barangay_list: [
            "ALUSIIS",
            "BEDDENG",
            "CANDELARIA (POB.)",
            "DALLIPAWEN",
            "GRULLO",
            "LA PAZ",
            "LIBERTAD (POB.)",
            "NAMATACAN",
            "NATIVIDAD (POB.)",
            "OMAYA",
            "PAITE",
            "PATROCINIO (POB.)",
            "SAN JOSE (POB.)",
            "SAN JUAN (POB.)",
            "SAN PASCUAL (POB.)",
            "SAN RAFAEL (POB.)",
            "SIMINUBLAN",
          ],
        },
        "SANTA CRUZ": {
          barangay_list: [
            "BABUYAN",
            "BANGCOL",
            "BAYTO",
            "BIAY",
            "BOLITOC",
            "BULAWON",
            "CANAYNAYAN",
            "GAMA",
            "GUINABON",
            "GUISGUIS",
            "LIPAY",
            "LOMBOY",
            "LUCAPON NORTH",
            "LUCAPON SOUTH",
            "MALABAGO",
            "NAULO",
            "PAGATPAT",
            "PAMONORAN",
            "POBLACION NORTH",
            "POBLACION SOUTH",
            "SABANG",
            "SAN FERNANDO",
            "TABALONG",
            "TUBOTUBO NORTH",
            "TUBOTUBO SOUTH",
          ],
        },
        SUBIC: {
          barangay_list: [
            "ANINGWAY SACATIHAN",
            "ASINAN POBLACION",
            "ASINAN PROPER",
            "BARACA-CAMACHILE (POB.)",
            "BATIAWAN",
            "CALAPACUAN",
            "CALAPANDAYAN (POB.)",
            "CAWAG",
            "ILWAS (POB.)",
            "MANGAN-VACA",
            "MATAIN",
            "NAUGSOL",
            "PAMATAWAN",
            "SAN ISIDRO",
            "SANTO TOMAS",
            "WAWANDUE (POB.)",
          ],
        },
      },
    },
  };

  const [municipalityList, setMunicipalityList] = useState(
    defaultValues?.province
      ? provinceList[defaultValues.province].municipality_list
      : {}
  );

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="flex flex-col gap-2"
      autocomplete="off"
    >
      <p>Full Name</p>
      <input
        type="text"
        placeholder="-- insert an input --"
        className="rounded-lg"
        {...register("fullname", {})}
      />
      <p>Gender</p>
      <select {...register("gender")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        <option value="Male">Male</option>
        <option value="Female">Female</option>
        <option value="Prefer Not To Say">Prefer Not To Say</option>
      </select>
      <p>Age</p>
      <input
        type="number"
        placeholder="-- insert an input --"
        {...register("age", {})}
        className="rounded-lg"
      />
      <p>Religion</p>
      <input
        type="text"
        placeholder="-- insert an input --"
        {...register("religion", {})}
        className="rounded-lg"
      />
      <p>Course</p>
      <select {...register("course")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        <option value="BS-IT">BS-IT</option>
        {/* <option value="BL-IS">BL-IS</option> */}
      </select>
      <p>Year</p>
      <select {...register("year")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        <option value="1">1st</option>
        <option value="2">2nd</option>
        <option value="3">3rd</option>
        <option value="4">4th</option>
      </select>
      <p>Specialization</p>
      <select {...register("specialization")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        <option value="Not Applicable">Not Applicable</option>
        <option value="Business Analytics">Business Analytics</option>
        <option value="Service Management">Service Management</option>
        <option value="Web and Mobile Development">
          Web and Mobile Development
        </option>
      </select>
      <p>Section</p>
      <select {...register("section")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        {letters.map((letter) => (
          <option key={`Section_${letter}`} value={letter}>
            {letter}
          </option>
        ))}
      </select>
      <p>Province</p>
      <select
        {...register("province")}
        className="rounded-lg"
        onChange={(e) => {
          setMunicipalityList(provinceList[e.target.value].municipality_list);
        }}
      >
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        {Object.keys(provinceList).map((location) => (
          <option key={`Province_${location}`} value={location}>
            {location}
          </option>
        ))}
      </select>
      <p>Municipality</p>
      <select {...register("municipality")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        {Object.keys(municipalityList).map((location) => (
          <option key={`Municipality_${location}`} value={location}>
            {location}
          </option>
        ))}
      </select>
      {/* <p>Baranggay</p>
      <select {...register("baranggay")} className="rounded-lg">
        {barangayList.map((location) => (
          <option key={`Baranggay_${location}`} value={location}>
            {location}
          </option>
        ))}
      </select> */}

      <p>Type of Family</p>
      <select {...register("familyType")} className="rounded-lg">
        <option disabled selected value className="text-gray-400">
          {" "}
          -- select an option --{" "}
        </option>
        <option value="Nuclear Family">Nuclear Family</option>
        <option value=" Single"> Single</option>
        <option value=" Step Family"> Step Family</option>
        <option value="Extended Family">Extended Family</option>
        <option value="Grand Parent Family">Grand Parent Family</option>
      </select>
      <div className="text-sm">
        <p>* Nuclear Family (two adults with at least one child) </p>
        <p>
          * Single-Parent Families (only one adult who is raising children){" "}
        </p>
        <p>
          * Step Families (one single parent marries another single parent){" "}
        </p>
        <p>
          * Extended Families (family might include relative live in one roof){" "}
        </p>
        <p>* Grandparent Families (consists of grandparent raising children)</p>
      </div>
      <input
        className="p-2 mx-auto text-black bg-orange-400 rounded-lg cursor-pointer w-fit"
        type="submit"
      />
    </form>
  );
}
